const fs = require('fs');

const enStrings = {
  "seo_badge": "In-Browser Audio Extraction Engine",
  "seo_h1": "Free MP4 to MP3 Converter Online (320kbps) – Fast, Large Files & 100% Private",
  "seo_p1": "Welcome to the fastest, most private way to convert large MP4 to MP3 online free. Powered by in-browser WebAssembly, our offline audio extractor eliminates traditional upload bottlenecks, allowing you to extract audio from 500MB to 1GB+ video files directly in your computer's RAM with zero quality loss.",
  "seo_p2": "If you have ever used a traditional cloud-based video converter, you intimately understand the frustration of the upload bottleneck. You wait ten minutes to upload a heavy, high-definition video file, hit an arbitrary premium file-size cap, deal with dropped connections, and ultimately download a severely compressed, watermarked audio file. As audio engineers and developers, we recognized that sending gigabytes of video data over the internet just to extract a tiny audio stream is profoundly inefficient.",
  "seo_p3": "We engineered this mp4 to mp3 converter without uploading to fundamentally change that pipeline. By leveraging a WebAssembly-compiled port of the industry-standard FFmpeg engine, our tool demuxes and encodes your media entirely client-side. This means you can convert 1gb video to mp3 online instantly—without the video ever leaving your local machine. It represents the pinnacle of privacy, speed, and fidelity, delivering true offline desktop performance directly within your web browser.",
  "seo_h2_1": "How It Works: Zero-Upload Technology",
  "seo_step1_title": "Local Input",
  "seo_step1_desc": "Drag and drop your MP4, MOV, MKV, AVI, or WebM clips directly into the dropzone. Because our engine operates entirely locally, there is absolutely no network upload phase. The file is instantly read into your browser's secure memory. You can queue a single file or utilize our bulk mp4 to mp3 converter online free capabilities for an entire batch.",
  "seo_step2_title": "FFmpeg Demuxing",
  "seo_step2_desc": "Instead of waiting on a remote server, a local WebAssembly module initializes. It rapidly parses the video container (like an MP4 or MKV shell) and locates the internal audio track (usually AAC or Opus). It strips away the heavy video data, isolating just the sound wave.",
  "seo_step3_title": "Transcoding & Export",
  "seo_step3_desc": "The extracted audio is transcoded to your selected bitrate (up to 320kbps). Once complete, a secure blob URL is generated locally, allowing you to save the MP3 directly to your hard drive or smartphone instantly.",
  "seo_h2_2": "Why Quality Matters: 320kbps vs 128kbps",
  "seo_quality_desc": "For music videos, live band performances, or cinematic trailers, you should unequivocally choose to use our mp4 to mp3 converter 320kbps no limit preset. At 320kbps CBR (Constant Bitrate), the encoder allocates maximum data to complex acoustic waves, retaining brilliant frequency clarity all the way up to 20 kHz. This eliminates the 'swishy' cymbals and muddy bass often caused by aggressive compression algorithms.",
  "seo_h2_3": "Supported Video Formats",
  "seo_formats_desc": "Our WebAssembly engine acts as a universal demuxer. It is capable of stripping audio from nearly every modern multimedia container.",
  "seo_format_mp4": "The standard format for iPhone, Android, and web video.",
  "seo_format_mkv": "Often used for high-definition movies and screen recordings.",
  "seo_format_mov": "Apple's QuickTime format, standard on macOS and iOS.",
  "seo_format_webm": "The open web standard, heavily used by YouTube and OBS.",
  "seo_format_avi": "Legacy Windows format still common in archival footage.",
  "seo_h2_4": "Cross-Platform Compatibility",
  "seo_compat_ios_title": "iPhone & iPad",
  "seo_compat_ios_desc": "You can grab an MP4 screen recording directly from your Photos app or Files directory, extract the audio locally, and save it straight back to your device.",
  "seo_compat_mac_title": "macOS & Windows Desktop",
  "seo_compat_mac_desc": "When you convert mp4 to mp3 on mac online free or Windows using Chrome, Edge, or Safari, you unlock the full multi-threaded power of your CPU. This makes parsing massive 2-hour OBS gaming streams or full-length movie trailers remarkably fast, effectively replacing bulky legacy desktop software.",
  "seo_compat_android_title": "Android Ecosystem",
  "seo_compat_android_desc": "If you need to convert mp4 to mp3 on android browser, Chrome for Android handles the memory allocation perfectly. It's an ideal workflow for journalists and students looking to rapidly extract audio from smartphone video recordings while out in the field without relying on a strong cellular connection.",
  "seo_h2_5": "Professional Audio Extraction Workflows",
  "seo_workflow_desc": "As a highly flexible mp4 audio extractor online free no watermark tool, this platform is utilized daily by thousands of content creators, educators, and professionals for a variety of demanding technical tasks:",
  "seo_wf1_title": "Corporate Meetings & Lectures",
  "seo_wf1_desc": "Rapidly converting bloated, hour-long Zoom, Microsoft Teams, or Google Meet video recordings into compact MP3s that can be easily uploaded to transcription software or shared via email attachments.",
  "seo_wf2_title": "Content Creation & Video Editing",
  "seo_wf2_desc": "When you convert screen recording mp4 to mp3, you can easily separate background music, in-game audio, or sound effects from OBS video captures to clean them up in external DAWs before the final video render.",
  "seo_wf3_title": "Offline Study & Podcasts",
  "seo_wf3_desc": "Extracting the audio track from downloaded tutorial videos, documentary clips, and lecture recordings so they can be securely listened to on mobile devices during commutes while conserving battery and screen time.",
  "seo_wf4_title": "Batch Archival",
  "seo_wf4_desc": "Utilizing our batch convert mp4 to mp3 in browser capabilities to process dozens of legacy family video clips at once, archiving the nostalgic audio memories into a single, organized ZIP file in seconds.",
  "seo_faq_title": "Frequently Asked Questions",
  "seo_faq1_q": "How do I convert large MP4 files to MP3 without waiting for slow cloud uploads?",
  "seo_faq1_a": "You can bypass slow cloud uploads entirely by using our client-side WebAssembly tool. Because it operates entirely within your browser's local memory ecosystem, your large video files are never transferred over the internet. You simply drag the file into the window, and the extraction process begins instantaneously using your device's native CPU hardware.",
  "seo_faq2_q": "Does extracting audio from a video reduce the sound quality?",
  "seo_faq2_a": "No, it does not have to. When you select our 320kbps CBR configuration, the LAME encoder transcodes the demuxed audio stream at the highest fidelity standard available for the MP3 format. This ensures that a vast majority of the original frequency spectrum and dynamic range is preserved perfectly, making it mathematically indistinguishable from the source to the human ear.",
  "seo_faq3_q": "Can I convert MP4 to MP3 on an iPhone without installing an app?",
  "seo_faq3_a": "Absolutely. Our application is fully compatible with Apple's iOS ecosystem. Simply open Safari or Chrome on your iPhone, navigate to our extractor, and select your video from the native iOS file picker or photo library. The WebAssembly engine will process the video securely on your phone and offer a direct MP3 download straight to your local Files app.",
  "seo_faq4_q": "Is there any file size limit or watermark added to the converted MP3?",
  "seo_faq4_a": "There are absolutely no artificial file size limits, subscription paywalls, or watermarks added to your audio. Because the processing is completely decentralized and offloaded to your computer's hardware, we do not incur expensive cloud server costs. The only limitation is the amount of available free RAM on your device for buffering the video data.",
  "seo_faq5_q": "Are my private video recordings safe and protected during conversion?",
  "seo_faq5_a": "Your data remains 100% private and protected. Our tool operates on a strict zero-upload architecture. Your Zoom recordings, proprietary business footage, and personal family videos never leave your hard drive. There are no remote cloud servers, no data retention policies, and no network eavesdropping risks, offering airtight privacy by design."
};

const esStrings = {
  "seo_badge": "Motor de Extracción de Audio en Navegador",
  "seo_h1": "Conversor de MP4 a MP3 Gratis Online (320kbps) – Rápido, Archivos Grandes y 100% Privado",
  "seo_p1": "Bienvenido a la forma más rápida y privada de convertir MP4 a MP3 online gratis. Impulsado por WebAssembly en el navegador, nuestro extractor de audio sin conexión elimina los cuellos de botella de subida, permitiendo extraer audio de videos de 500MB a 1GB+ directamente en la RAM sin pérdida de calidad.",
  "seo_p2": "Si alguna vez usaste un conversor en la nube tradicional, entiendes la frustración. Esperar 10 minutos, límites de tamaño, conexiones caídas y finalmente descargar un archivo comprimido con marca de agua. Es muy ineficiente.",
  "seo_p3": "Diseñamos este conversor sin subidas para cambiar eso. Usando FFmpeg en WebAssembly, la herramienta demultiplexa y codifica totalmente en el cliente. Puedes convertir videos de 1GB al instante, sin que el archivo salga de tu máquina.",
  "seo_h2_1": "Cómo Funciona: Tecnología Sin Subidas",
  "seo_step1_title": "Entrada Local",
  "seo_step1_desc": "Arrastra y suelta tus videos MP4, MOV, MKV, AVI, o WebM. Al operar localmente, no hay fase de subida. Puedes poner un archivo en cola o usar el conversor masivo.",
  "seo_step2_title": "Demultiplexación FFmpeg",
  "seo_step2_desc": "En lugar de esperar un servidor remoto, un módulo WebAssembly se inicializa localmente. Analiza el video y localiza la pista de audio (AAC u Opus), separando solo la onda de sonido.",
  "seo_step3_title": "Transcodificación y Exportación",
  "seo_step3_desc": "El audio extraído se transcodifica a tu bitrate (hasta 320kbps). Se genera una URL segura local para descargar el MP3 instantáneamente.",
  "seo_h2_2": "Por qué la Calidad Importa: 320kbps vs 128kbps",
  "seo_quality_desc": "Para videos musicales o trailers, debes elegir nuestro preset de 320kbps. A esta velocidad, el codificador asigna el máximo de datos a ondas acústicas complejas, reteniendo claridad hasta los 20 kHz.",
  "seo_h2_3": "Formatos de Video Soportados",
  "seo_formats_desc": "Nuestro motor WebAssembly actúa como demultiplexador universal.",
  "seo_format_mp4": "Formato estándar para iPhone, Android y web.",
  "seo_format_mkv": "Usado para películas de alta definición y grabaciones.",
  "seo_format_mov": "Formato QuickTime de Apple, estándar en macOS e iOS.",
  "seo_format_webm": "Estándar web abierto, usado por YouTube y OBS.",
  "seo_format_avi": "Formato legado de Windows, común en archivos.",
  "seo_h2_4": "Compatibilidad Multiplataforma",
  "seo_compat_ios_title": "iPhone & iPad",
  "seo_compat_ios_desc": "Puedes usar una grabación de pantalla MP4 de Fotos o Archivos, extraer el audio localmente y guardarlo en tu dispositivo.",
  "seo_compat_mac_title": "macOS & Windows Desktop",
  "seo_compat_mac_desc": "Al convertir en Mac o Windows, desbloqueas todo el poder de tu CPU, reemplazando software de escritorio lento y pesado.",
  "seo_compat_android_title": "Ecosistema Android",
  "seo_compat_android_desc": "Ideal para periodistas o estudiantes que extraen audio desde su móvil sin conexión a internet rápida.",
  "seo_h2_5": "Casos de Uso Profesionales",
  "seo_workflow_desc": "Esta plataforma es usada por creadores y profesionales para múltiples tareas:",
  "seo_wf1_title": "Reuniones y Clases",
  "seo_wf1_desc": "Convierte horas de video de Zoom, Teams o Meet en MP3s compactos para transcripciones o compartir por email.",
  "seo_wf2_title": "Edición de Video y Creación",
  "seo_wf2_desc": "Separa música de fondo, audio de juegos o efectos de captura de OBS para limpiar el audio en un DAW.",
  "seo_wf3_title": "Estudio Offline & Podcasts",
  "seo_wf3_desc": "Extrae audio de tutoriales, documentales y clases para escucharlo en móviles mientras ahorras batería y datos.",
  "seo_wf4_title": "Archivo Masivo",
  "seo_wf4_desc": "Usa la función de conversión masiva para decenas de clips familiares a la vez, archivándolos en un solo ZIP.",
  "seo_faq_title": "Preguntas Frecuentes",
  "seo_faq1_q": "¿Cómo convertir grandes archivos MP4 a MP3 sin esperar la subida?",
  "seo_faq1_a": "Nuestra herramienta procesa el video en la memoria local del navegador, por lo que nunca se sube a internet. Usamos tu CPU para procesarlo al instante.",
  "seo_faq2_q": "¿Extraer el audio de un video reduce la calidad?",
  "seo_faq2_a": "No necesariamente. Al seleccionar 320kbps CBR, se codifica a la máxima fidelidad del formato MP3, preservando perfectamente el espectro original.",
  "seo_faq3_q": "¿Puedo convertir MP4 a MP3 en un iPhone sin app?",
  "seo_faq3_a": "Absolutamente. Abre Safari o Chrome, selecciona tu video de la galería y descárgalo directo en tus archivos.",
  "seo_faq4_q": "¿Hay un límite de tamaño o marca de agua?",
  "seo_faq4_a": "No hay límites, muros de pago ni marcas de agua. Como procesa en tu dispositivo, no hay costos de servidor.",
  "seo_faq5_q": "¿Están seguros mis videos?",
  "seo_faq5_a": "Tus datos permanecen 100% privados. La arquitectura no usa subidas; todo se procesa en tu disco duro."
};

const frStrings = {
  "seo_badge": "Moteur d'Extraction Audio Navigateur",
  "seo_h1": "Convertisseur MP4 en MP3 Gratuit en Ligne (320kbps) – Rapide, 100% Privé",
  "seo_p1": "Bienvenue dans le moyen le plus rapide et privé de convertir de grands MP4 en MP3. Notre extracteur hors ligne propulsé par WebAssembly élimine les temps de téléversement et convertit directement dans la RAM.",
  "seo_p2": "Les convertisseurs cloud traditionnels sont lents, limités en taille et réduisent la qualité de l'audio. Envoyer des Go de vidéo juste pour extraire de l'audio est inefficace.",
  "seo_p3": "Nous avons conçu cet outil pour tout traiter côté client via FFmpeg WebAssembly. Convertissez instantanément sans que la vidéo ne quitte votre machine.",
  "seo_h2_1": "Comment ça marche : Zéro Téléversement",
  "seo_step1_title": "Entrée Locale",
  "seo_step1_desc": "Glissez vos vidéos MP4, MOV, MKV, AVI ou WebM. Le traitement est local, pas de phase de téléversement.",
  "seo_step2_title": "Démultiplexage FFmpeg",
  "seo_step2_desc": "Le module WebAssembly analyse le conteneur vidéo et isole la piste audio (AAC ou Opus).",
  "seo_step3_title": "Transcodage & Export",
  "seo_step3_desc": "L'audio est transcodé au bitrate sélectionné. Téléchargez ensuite le MP3 instantanément.",
  "seo_h2_2": "Pourquoi la qualité est importante : 320kbps vs 128kbps",
  "seo_quality_desc": "Pour les clips musicaux ou performances live, choisissez 320kbps. Le codeur conserve la clarté jusqu'à 20 kHz.",
  "seo_h2_3": "Formats vidéo pris en charge",
  "seo_formats_desc": "Notre moteur peut extraire l'audio de presque tous les formats modernes.",
  "seo_format_mp4": "Le format standard pour iPhone, Android et le web.",
  "seo_format_mkv": "Souvent utilisé pour les films haute définition.",
  "seo_format_mov": "Le format QuickTime d'Apple, standard sur macOS.",
  "seo_format_webm": "Le standard web ouvert, très utilisé par YouTube et OBS.",
  "seo_format_avi": "Format Windows hérité encore commun.",
  "seo_h2_4": "Compatibilité Multiplateforme",
  "seo_compat_ios_title": "iPhone & iPad",
  "seo_compat_ios_desc": "Extrayez l'audio localement depuis l'application Photos ou Fichiers.",
  "seo_compat_mac_title": "macOS & Windows Desktop",
  "seo_compat_mac_desc": "Débloquez la puissance multicœur de votre CPU sur Chrome ou Safari pour remplacer les logiciels lourds.",
  "seo_compat_android_title": "Écosystème Android",
  "seo_compat_android_desc": "Idéal pour les journalistes sur le terrain sans connexion internet stable.",
  "seo_h2_5": "Cas d'Usage Professionnels",
  "seo_workflow_desc": "Notre outil est utilisé pour des tâches exigeantes :",
  "seo_wf1_title": "Réunions d'entreprise & Cours",
  "seo_wf1_desc": "Convertir des vidéos Zoom, Teams ou Meet en MP3 compacts pour transcriptions.",
  "seo_wf2_title": "Création de Contenu",
  "seo_wf2_desc": "Séparer l'audio des vidéos pour le nettoyer avant montage.",
  "seo_wf3_title": "Étude hors ligne & Podcasts",
  "seo_wf3_desc": "Écouter des cours ou tutoriels sur téléphone sans utiliser l'écran.",
  "seo_wf4_title": "Archivage en lots",
  "seo_wf4_desc": "Convertir des dizaines de vidéos familiales en une seule fois.",
  "seo_faq_title": "Foire Aux Questions",
  "seo_faq1_q": "Comment convertir sans attendre le téléversement ?",
  "seo_faq1_a": "L'outil traite la vidéo localement dans votre RAM. La vidéo n'est jamais envoyée sur internet.",
  "seo_faq2_q": "L'extraction réduit-elle la qualité du son ?",
  "seo_faq2_a": "Non. En choisissant 320kbps CBR, vous conservez la meilleure fidélité MP3.",
  "seo_faq3_q": "Puis-je l'utiliser sur iPhone sans application ?",
  "seo_faq3_a": "Oui, via Safari ou Chrome, l'audio est traité sur le téléphone et téléchargé dans vos fichiers.",
  "seo_faq4_q": "Y a-t-il une limite de taille ou un filigrane ?",
  "seo_faq4_a": "Aucune limite, ni filigrane. Pas de coûts de serveurs externes.",
  "seo_faq5_q": "Mes vidéos privées sont-elles sécurisées ?",
  "seo_faq5_a": "Elles restent 100% privées. Il n'y a aucun serveur distant."
};

const deStrings = {
  "seo_badge": "In-Browser Audio Extraction Engine",
  "seo_h1": "Kostenloser MP4 zu MP3 Konverter Online (320kbps) – Schnell, große Dateien & 100% privat",
  "seo_p1": "Willkommen beim schnellsten, privatesten Weg zur Konvertierung. Dank WebAssembly im Browser werden Uploads hinfällig und die Qualität bleibt erhalten.",
  "seo_p2": "Herkömmliche Cloud-Konverter haben nervige Wartezeiten, Limits und Wasserzeichen. Das Senden von Videodaten ins Internet ist ineffizient.",
  "seo_p3": "Unser Konverter macht alles lokal auf Ihrem PC. Konvertieren Sie 1GB sofort, ohne dass die Datei das Gerät verlässt.",
  "seo_h2_1": "Wie es funktioniert: Zero-Upload-Technologie",
  "seo_step1_title": "Lokale Eingabe",
  "seo_step1_desc": "Ziehen Sie MP4, MOV, MKV, AVI oder WebM per Drag & Drop. Keine Wartezeit.",
  "seo_step2_title": "FFmpeg Demuxing",
  "seo_step2_desc": "Das WebAssembly-Modul analysiert das Video und extrahiert die Audiospur.",
  "seo_step3_title": "Transcodierung & Export",
  "seo_step3_desc": "Das Audio wird ins MP3-Format umgewandelt und lokal gespeichert.",
  "seo_h2_2": "Warum Qualität wichtig ist: 320kbps",
  "seo_quality_desc": "Für Musik wählen Sie das 320kbps Preset für maximale Klangtreue ohne Beschneidung der hohen Frequenzen.",
  "seo_h2_3": "Unterstützte Videoformate",
  "seo_formats_desc": "Unsere Engine unterstützt alle gängigen Formate:",
  "seo_format_mp4": "Standardformat für Smartphones und Web.",
  "seo_format_mkv": "Oft für HD-Filme verwendet.",
  "seo_format_mov": "Apples QuickTime-Format.",
  "seo_format_webm": "Offener Webstandard (YouTube/OBS).",
  "seo_format_avi": "Älteres Windows-Format.",
  "seo_h2_4": "Plattformübergreifende Kompatibilität",
  "seo_compat_ios_title": "iPhone & iPad",
  "seo_compat_ios_desc": "Direkt aus der Fotos-App verarbeiten.",
  "seo_compat_mac_title": "macOS & Windows Desktop",
  "seo_compat_mac_desc": "Nutzt die volle CPU-Leistung, perfekt für OBS Streams.",
  "seo_compat_android_title": "Android Ecosystem",
  "seo_compat_android_desc": "Perfekt für Journalisten unterwegs.",
  "seo_h2_5": "Professionelle Audio-Workflows",
  "seo_workflow_desc": "Täglich von Profis genutzt für:",
  "seo_wf1_title": "Meetings & Vorlesungen",
  "seo_wf1_desc": "Zoom-Aufnahmen in kleine MP3s zur Transkription umwandeln.",
  "seo_wf2_title": "Videobearbeitung",
  "seo_wf2_desc": "Audio vom Video trennen für externe DAWs.",
  "seo_wf3_title": "Offline-Lernen",
  "seo_wf3_desc": "Tutorials als MP3 für unterwegs ohne Bildschirmzeit.",
  "seo_wf4_title": "Batch-Archivierung",
  "seo_wf4_desc": "Mehrere Clips gleichzeitig in ein ZIP packen.",
  "seo_faq_title": "Häufig gestellte Fragen (FAQ)",
  "seo_faq1_q": "Wie konvertiere ich große MP4s ohne Upload?",
  "seo_faq1_a": "Das Tool arbeitet komplett lokal im Browser-Speicher. Nichts wird ins Internet gesendet.",
  "seo_faq2_q": "Reduziert die Extraktion die Audioqualität?",
  "seo_faq2_a": "Nein, mit 320kbps CBR bleibt die maximale MP3-Qualität erhalten.",
  "seo_faq3_q": "Funktioniert es auf dem iPhone ohne App?",
  "seo_faq3_a": "Ja, direkt in Safari oder Chrome.",
  "seo_faq4_q": "Gibt es ein Größenlimit oder Wasserzeichen?",
  "seo_faq4_a": "Keine Limits, keine Kosten, keine Wasserzeichen.",
  "seo_faq5_q": "Sind meine Videos sicher?",
  "seo_faq5_a": "100% privat, da keine Daten das Gerät verlassen."
};

const ptStrings = {
  "seo_badge": "Mecanismo de Extração de Áudio no Navegador",
  "seo_h1": "Conversor de MP4 para MP3 Grátis Online (320kbps) – Rápido, Arquivos Grandes e 100% Privado",
  "seo_p1": "A maneira mais rápida e privada de converter vídeos. Com WebAssembly, eliminamos os uploads.",
  "seo_p2": "Conversores na nuvem são lentos, têm limites e perdem qualidade. Enviar GB de dados pela internet é ineficiente.",
  "seo_p3": "Construímos esta ferramenta para funcionar 100% offline no seu navegador.",
  "seo_h2_1": "Como Funciona: Zero Upload",
  "seo_step1_title": "Entrada Local",
  "seo_step1_desc": "Arraste e solte arquivos MP4, MOV, MKV, AVI ou WebM.",
  "seo_step2_title": "Demuxing FFmpeg",
  "seo_step2_desc": "O WebAssembly analisa o vídeo e extrai a faixa de áudio instantaneamente.",
  "seo_step3_title": "Transcodificação e Exportação",
  "seo_step3_desc": "O áudio é transcodificado para o bitrate desejado.",
  "seo_h2_2": "Por que a Qualidade Importa: 320kbps",
  "seo_quality_desc": "Para a máxima fidelidade, escolha 320kbps. Mantém a clareza até 20 kHz.",
  "seo_h2_3": "Formatos Suportados",
  "seo_formats_desc": "Suportamos praticamente todos os formatos modernos:",
  "seo_format_mp4": "Formato padrão de celulares e web.",
  "seo_format_mkv": "Usado para filmes HD e gravações.",
  "seo_format_mov": "Formato QuickTime da Apple.",
  "seo_format_webm": "Padrão da web aberta (YouTube/OBS).",
  "seo_format_avi": "Formato Windows antigo.",
  "seo_h2_4": "Compatibilidade Multiplataforma",
  "seo_compat_ios_title": "iPhone & iPad",
  "seo_compat_ios_desc": "Funciona direto do app Fotos ou Arquivos.",
  "seo_compat_mac_title": "macOS & Windows Desktop",
  "seo_compat_mac_desc": "Aproveite a velocidade total da CPU do seu PC.",
  "seo_compat_android_title": "Ecossistema Android",
  "seo_compat_android_desc": "Ótimo para jornalistas sem boa conexão à internet.",
  "seo_h2_5": "Casos de Uso Profissionais",
  "seo_workflow_desc": "Usado diariamente por criadores e profissionais:",
  "seo_wf1_title": "Reuniões Corporativas",
  "seo_wf1_desc": "Converter gravações do Zoom para MP3 leve.",
  "seo_wf2_title": "Edição de Vídeo",
  "seo_wf2_desc": "Separar música ou áudio de jogo do vídeo.",
  "seo_wf3_title": "Estudo Offline",
  "seo_wf3_desc": "Ouvir tutoriais e palestras economizando bateria.",
  "seo_wf4_title": "Arquivamento em Lote",
  "seo_wf4_desc": "Converter dezenas de vídeos em ZIP de uma só vez.",
  "seo_faq_title": "Perguntas Frequentes",
  "seo_faq1_q": "Como converter MP4s grandes sem demora no upload?",
  "seo_faq1_a": "Nossa ferramenta processa tudo localmente na sua RAM.",
  "seo_faq2_q": "Extrair o áudio reduz a qualidade?",
  "seo_faq2_a": "Não. O MP3 a 320kbps mantém a fidelidade original.",
  "seo_faq3_q": "Posso usar no iPhone sem app?",
  "seo_faq3_a": "Sim, funciona no Safari e Chrome de forma nativa.",
  "seo_faq4_q": "Há limite de tamanho ou marca d'água?",
  "seo_faq4_a": "Não há limites, marcas d'água ou assinaturas.",
  "seo_faq5_q": "Meus vídeos privados estão seguros?",
  "seo_faq5_a": "100% seguros, já que não usamos servidores na nuvem."
};

const translations = {
  en: enStrings,
  es: esStrings,
  fr: frStrings,
  de: deStrings,
  pt: ptStrings
};

for (const [lang, strings] of Object.entries(translations)) {
  const filePath = `messages/${lang}.json`;
  if (fs.existsSync(filePath)) {
    const data = JSON.parse(fs.readFileSync(filePath, 'utf8'));
    data.video_seo = strings;
    fs.writeFileSync(filePath, JSON.stringify(data, null, 2));
  }
}
