import json

en_translations = {
    "mp3_to_m4a": {
        "meta_title": "Free MP3 to M4A Converter Online",
        "meta_description": "Convert MP3 to M4A online for free at up to 256kbps and 320kbps. Fast, client-side batch audio conversion in your browser with zero server uploads.",
        "h1": "Free <highlight>MP3 to M4A</highlight> Converter Online",
        "subtitle": "Convert MP3 tracks to M4A (AAC) instantly using advanced WebAssembly technology right in your browser. Experience fast, seamless conversion with absolute data privacy—zero cloud uploads and zero file size limits.",
        "step_title": "How to Convert MP3 to M4A in 3 Simple Steps",
        "step1_title": "Upload Audio",
        "step1_desc": "Drag & drop single or multiple MP3 audio files into the secure conversion zone above.",
        "step2_title": "Select Bitrate",
        "step2_desc": "Choose your desired AAC bitrate preset (128 kbps, 192 kbps, 256 kbps, or 320 kbps) for optimal quality.",
        "step3_title": "Convert & Download",
        "step3_desc": "Click convert and download individual M4A tracks or batch export as a convenient ZIP file instantly.",
        "why_title": "Why Convert MP3 to AAC/M4A?",
        "why_p1": "While MP3 has been the standard for decades, it is functionally a legacy format. Converting your files to the M4A container (using the advanced AAC codec) provides significant technical advantages. AAC was designed to be the successor to MP3, offering superior acoustic efficiency and broader frequency spectrum retention at lower file sizes.",
        "why_p2": "If you are entrenched in the Apple ecosystem, this format is highly recommended. M4A offers seamless playback across Apple devices like the iPhone, iPad, Mac, and iTunes. Additionally, if you need a reliable <bold>mp3 to m4a ringtone converter</bold>, standardizing your files to M4A ensures perfect compatibility with modern mobile operating systems.",
        "bitrate_title": "Detailed Bitrate & Quality Guide",
        "bitrate_th1": "Preset Bitrate",
        "bitrate_th2": "Codec Standard",
        "bitrate_th3": "Best Use Case",
        "bitrate_th4": "Relative File Size & Quality",
        "bitrate_128_use": "Voice / Podcasts",
        "bitrate_128_desc": "Smallest size; acceptable acoustic quality for speech.",
        "bitrate_192_use": "Everyday Listening",
        "bitrate_192_desc": "Balanced size; transparent quality for standard car speakers or casual earbuds.",
        "bitrate_256_use": "Apple Music Standard",
        "bitrate_256_desc": "Slightly larger; practically indistinguishable from the original CD source for most listeners.",
        "bitrate_320_use": "Studio / Orchestral",
        "bitrate_320_desc": "Largest size; preserves complex frequency details for high-end acoustic gear.",
        "features_title": "Key Features of Our Client-Side Audio Engine",
        "feat1_title": "100% Client-Side Privacy",
        "feat1_desc": "No audio data ever touches a remote server. When you use this <bold>mp3 to m4a converter online free</bold>, all processing occurs directly in your browser.",
        "feat2_title": "Batch Processing",
        "feat2_desc": "Convert dozens of files simultaneously without server queue delays. This is the fastest <bold>batch mp3 to m4a converter online</bold> available.",
        "feat3_title": "Preserved Audio Metadata",
        "feat3_desc": "Retains your crucial ID3 tags (Artist, Album, Title) mapped automatically to MP4 atoms during the conversion process.",
        "feat4_title": "No Software Installation",
        "feat4_desc": "Seamlessly <bold>convert mp3 to aac m4a in browser</bold> across all modern desktop and mobile operating systems natively.",
        "faq_title": "Frequently Asked Questions",
        "faq1_q": "How to convert MP3 to M4A without losing sound quality?",
        "faq1_a": "To <bold>convert mp3 to m4a without losing sound quality</bold>, you should match or slightly exceed the original bitrate of your MP3 file. For example, if your MP3 is 192kbps, selecting the 192kbps or <bold>mp3 to m4a 256kbps online</bold> preset ensures that you preserve all audible acoustic data during the codec transition.",
        "faq2_q": "Is there a file size limit when converting large audio files?",
        "faq2_a": "No. Because our engine operates entirely locally within your browser, there are no artificial caps. You can easily <bold>convert large mp3 to m4a online without server upload</bold> restrictions, limited only by your device's available RAM and processing power. It is the <bold>best mp3 to m4a audio converter online free no limit</bold> solution available.",
        "faq3_q": "Can I convert MP3 to M4A directly on iPhone without downloading an app?",
        "faq3_a": "Yes, you can absolutely <bold>convert mp3 to m4a on iphone</bold> directly through Safari. Since the tool relies on modern WebAssembly and the Web Audio API, the entire process runs natively in your mobile browser, saving you from downloading bulky third-party applications.",
        "faq4_q": "Why is 256kbps AAC considered better than 320kbps MP3?",
        "faq4_a": "AAC (the audio codec used inside M4A files) is a much newer and more efficient algorithm than MP3. A 256kbps AAC file retains high-frequency clarity and transient details better than a legacy 320kbps MP3, while typically resulting in a smaller overall file size. This is why Apple Music uses 256kbps AAC as their standard encoding format.",
        "faq5_q": "Are my audio files uploaded to your server during conversion?",
        "faq5_a": "Never. Our architecture guarantees a <bold>fast mp3 to m4a without uploading</bold> experience. Your files remain entirely on your local hard drive or mobile storage. The conversion happens strictly client-side, ensuring your personal audio and intellectual property are completely private."
    }
}

es_translations = {
    "mp3_to_m4a": {
        "meta_title": "Convertidor de MP3 a M4A Gratis en Línea",
        "meta_description": "Convierte MP3 a M4A en línea gratis hasta a 256kbps y 320kbps. Conversión de audio por lotes rápida y del lado del cliente en tu navegador sin subidas al servidor.",
        "h1": "Convertidor de <highlight>MP3 a M4A</highlight> Gratis en Línea",
        "subtitle": "Convierte pistas MP3 a M4A (AAC) instantáneamente usando tecnología avanzada de WebAssembly directamente en tu navegador. Experimenta una conversión rápida y fluida con total privacidad de datos: sin subidas a la nube y sin límites de tamaño de archivo.",
        "step_title": "Cómo Convertir MP3 a M4A en 3 Sencillos Pasos",
        "step1_title": "Subir Audio",
        "step1_desc": "Arrastra y suelta uno o varios archivos de audio MP3 en la zona de conversión segura de arriba.",
        "step2_title": "Seleccionar Tasa de Bits",
        "step2_desc": "Elige el preajuste de tasa de bits AAC deseado (128 kbps, 192 kbps, 256 kbps o 320 kbps) para una calidad óptima.",
        "step3_title": "Convertir y Descargar",
        "step3_desc": "Haz clic en convertir y descarga pistas M4A individuales o expórtalas por lotes como un archivo ZIP al instante.",
        "why_title": "¿Por qué Convertir MP3 a AAC/M4A?",
        "why_p1": "Aunque el MP3 ha sido el estándar durante décadas, funcionalmente es un formato heredado. Convertir tus archivos al contenedor M4A (usando el códec avanzado AAC) proporciona ventajas técnicas significativas. AAC fue diseñado para ser el sucesor del MP3, ofreciendo una eficiencia acústica superior y una mayor retención del espectro de frecuencia con tamaños de archivo más pequeños.",
        "why_p2": "Si estás inmerso en el ecosistema de Apple, este formato es muy recomendable. M4A ofrece una reproducción perfecta en dispositivos Apple como iPhone, iPad, Mac e iTunes. Además, si necesitas un <bold>convertidor de tonos mp3 a m4a</bold> confiable, estandarizar tus archivos a M4A garantiza una compatibilidad perfecta con los sistemas operativos móviles modernos.",
        "bitrate_title": "Guía Detallada de Tasa de Bits y Calidad",
        "bitrate_th1": "Tasa de Bits (Preajuste)",
        "bitrate_th2": "Estándar de Códec",
        "bitrate_th3": "Mejor Caso de Uso",
        "bitrate_th4": "Tamaño de Archivo Relativo y Calidad",
        "bitrate_128_use": "Voz / Podcasts",
        "bitrate_128_desc": "Tamaño más pequeño; calidad acústica aceptable para voz.",
        "bitrate_192_use": "Escucha Diaria",
        "bitrate_192_desc": "Tamaño equilibrado; calidad transparente para altavoces de coche estándar o auriculares casuales.",
        "bitrate_256_use": "Estándar de Apple Music",
        "bitrate_256_desc": "Ligeramente más grande; prácticamente indistinguible de la fuente original en CD para la mayoría de los oyentes.",
        "bitrate_320_use": "Estudio / Orquestal",
        "bitrate_320_desc": "Tamaño más grande; preserva detalles de frecuencia complejos para equipos acústicos de alta gama.",
        "features_title": "Características Clave de Nuestro Motor de Audio del Lado del Cliente",
        "feat1_title": "Privacidad 100% del Lado del Cliente",
        "feat1_desc": "Ningún dato de audio toca jamás un servidor remoto. Cuando usas este <bold>convertidor mp3 a m4a online gratis</bold>, todo el procesamiento ocurre directamente en tu navegador.",
        "feat2_title": "Procesamiento por Lotes",
        "feat2_desc": "Convierte docenas de archivos simultáneamente sin demoras por colas en el servidor. Este es el <bold>convertidor mp3 a m4a por lotes en línea</bold> más rápido disponible.",
        "feat3_title": "Metadatos de Audio Preservados",
        "feat3_desc": "Retiene tus etiquetas ID3 cruciales (Artista, Álbum, Título) mapeadas automáticamente a los átomos MP4 durante el proceso de conversión.",
        "feat4_title": "Sin Instalación de Software",
        "feat4_desc": "Convierte <bold>mp3 a aac m4a en el navegador</bold> sin problemas en todos los sistemas operativos móviles y de escritorio modernos de forma nativa.",
        "faq_title": "Preguntas Frecuentes",
        "faq1_q": "¿Cómo convertir MP3 a M4A sin perder calidad de sonido?",
        "faq1_a": "Para <bold>convertir mp3 a m4a sin perder calidad de sonido</bold>, debes igualar o superar ligeramente la tasa de bits original de tu archivo MP3. Por ejemplo, si tu MP3 es de 192kbps, seleccionar el preajuste de 192kbps o <bold>mp3 a m4a 256kbps en línea</bold> garantiza que preserves todos los datos acústicos audibles durante la transición del códec.",
        "faq2_q": "¿Existe un límite de tamaño de archivo al convertir archivos de audio grandes?",
        "faq2_a": "No. Debido a que nuestro motor opera de manera completamente local dentro de tu navegador, no hay límites artificiales. Puedes <bold>convertir archivos mp3 grandes a m4a en línea sin subir al servidor</bold> fácilmente, limitado solo por la memoria RAM y la potencia de procesamiento disponible de tu dispositivo. Es la <bold>mejor solución de convertidor de audio mp3 a m4a en línea gratis sin límite</bold> disponible.",
        "faq3_q": "¿Puedo convertir MP3 a M4A directamente en el iPhone sin descargar una aplicación?",
        "faq3_a": "Sí, absolutamente puedes <bold>convertir mp3 a m4a en iphone</bold> directamente a través de Safari. Dado que la herramienta se basa en la moderna tecnología WebAssembly y la API de Web Audio, todo el proceso se ejecuta de forma nativa en tu navegador móvil, evitando la descarga de aplicaciones voluminosas de terceros.",
        "faq4_q": "¿Por qué 256kbps AAC se considera mejor que 320kbps MP3?",
        "faq4_a": "AAC (el códec de audio utilizado dentro de los archivos M4A) es un algoritmo mucho más nuevo y eficiente que el MP3. Un archivo AAC de 256kbps retiene la claridad de las altas frecuencias y los detalles transitorios mejor que un MP3 heredado de 320kbps, resultando típicamente en un tamaño de archivo general más pequeño. Por esto, Apple Music utiliza AAC a 256kbps como su formato de codificación estándar.",
        "faq5_q": "¿Mis archivos de audio se suben a su servidor durante la conversión?",
        "faq5_a": "Nunca. Nuestra arquitectura garantiza una experiencia <bold>rápida de mp3 a m4a sin subir archivos</bold>. Tus archivos permanecen enteramente en tu disco duro local o almacenamiento móvil. La conversión se realiza estrictamente del lado del cliente, asegurando que tu audio personal y propiedad intelectual sean completamente privados."
    }
}

fr_translations = {
    "mp3_to_m4a": {
        "meta_title": "Convertisseur MP3 en M4A Gratuit en Ligne",
        "meta_description": "Convertissez des MP3 en M4A en ligne gratuitement jusqu'à 256 kbps et 320 kbps. Conversion audio par lots rapide, côté client dans votre navigateur sans téléversement sur serveur.",
        "h1": "Convertisseur <highlight>MP3 en M4A</highlight> Gratuit en Ligne",
        "subtitle": "Convertissez instantanément des pistes MP3 en M4A (AAC) grâce à la technologie avancée WebAssembly directement dans votre navigateur. Profitez d'une conversion rapide avec une confidentialité totale des données — aucun téléversement dans le cloud et aucune limite de taille de fichier.",
        "step_title": "Comment Convertir des MP3 en M4A en 3 Étapes Simples",
        "step1_title": "Uploader l'Audio",
        "step1_desc": "Glissez-déposez un ou plusieurs fichiers audio MP3 dans la zone de conversion sécurisée ci-dessus.",
        "step2_title": "Sélectionner le Débit Binaire",
        "step2_desc": "Choisissez votre préréglage de débit binaire AAC (128 kbps, 192 kbps, 256 kbps, ou 320 kbps) pour une qualité optimale.",
        "step3_title": "Convertir et Télécharger",
        "step3_desc": "Cliquez sur convertir et téléchargez les pistes M4A individuellement ou exportez-les par lots dans un fichier ZIP pratique instantanément.",
        "why_title": "Pourquoi Convertir un MP3 en AAC/M4A ?",
        "why_p1": "Bien que le MP3 ait été la norme pendant des décennies, c'est fonctionnellement un format obsolète. Convertir vos fichiers vers le conteneur M4A (utilisant le codec avancé AAC) offre des avantages techniques significatifs. AAC a été conçu pour succéder au MP3, offrant une efficacité acoustique supérieure et une meilleure préservation du spectre de fréquences avec des tailles de fichiers réduites.",
        "why_p2": "Si vous êtes investi dans l'écosystème Apple, ce format est fortement recommandé. Le M4A offre une lecture fluide sur les appareils Apple comme l'iPhone, l'iPad, le Mac et iTunes. De plus, si vous avez besoin d'un <bold>convertisseur de sonnerie mp3 en m4a</bold> fiable, standardiser vos fichiers en M4A garantit une compatibilité parfaite avec les systèmes d'exploitation mobiles modernes.",
        "bitrate_title": "Guide Détaillé des Débits Binaires & Qualité",
        "bitrate_th1": "Débit Binaire",
        "bitrate_th2": "Standard du Codec",
        "bitrate_th3": "Meilleur Cas d'Utilisation",
        "bitrate_th4": "Taille Relative du Fichier & Qualité",
        "bitrate_128_use": "Voix / Podcasts",
        "bitrate_128_desc": "Plus petite taille ; qualité acoustique acceptable pour la parole.",
        "bitrate_192_use": "Écoute Quotidienne",
        "bitrate_192_desc": "Taille équilibrée ; qualité transparente pour les haut-parleurs de voiture standards ou les écouteurs basiques.",
        "bitrate_256_use": "Standard Apple Music",
        "bitrate_256_desc": "Légèrement plus grand ; pratiquement indiscernable de la source CD originale pour la plupart des auditeurs.",
        "bitrate_320_use": "Studio / Orchestral",
        "bitrate_320_desc": "Plus grande taille ; préserve les détails de fréquences complexes pour les équipements acoustiques haut de gamme.",
        "features_title": "Caractéristiques Clés de Notre Moteur Audio Côté Client",
        "feat1_title": "Confidentialité 100% Côté Client",
        "feat1_desc": "Aucune donnée audio ne touche jamais un serveur distant. Lorsque vous utilisez ce <bold>convertisseur mp3 en m4a en ligne gratuit</bold>, tout le traitement s'effectue directement dans votre navigateur.",
        "feat2_title": "Traitement par Lots",
        "feat2_desc": "Convertissez des dizaines de fichiers simultanément sans délai d'attente sur serveur. C'est le <bold>convertisseur de lots mp3 en m4a en ligne</bold> le plus rapide disponible.",
        "feat3_title": "Métadonnées Audio Préservées",
        "feat3_desc": "Conserve vos précieuses balises ID3 (Artiste, Album, Titre) automatiquement assignées aux atomes MP4 pendant le processus de conversion.",
        "feat4_title": "Aucune Installation de Logiciel",
        "feat4_desc": "Convertissez sans faille des <bold>mp3 en aac m4a dans le navigateur</bold> sur tous les systèmes d'exploitation de bureau et mobiles modernes nativement.",
        "faq_title": "Foire Aux Questions",
        "faq1_q": "Comment convertir un MP3 en M4A sans perdre de qualité sonore ?",
        "faq1_a": "Pour <bold>convertir un mp3 en m4a sans perdre de qualité sonore</bold>, vous devez égaler ou dépasser légèrement le débit binaire original de votre fichier MP3. Par exemple, si votre MP3 est à 192kbps, choisir le préréglage 192kbps ou <bold>mp3 en m4a 256kbps en ligne</bold> assure de préserver toutes les données acoustiques audibles durant la transition du codec.",
        "faq2_q": "Y a-t-il une limite de taille lors de la conversion de gros fichiers audio ?",
        "faq2_a": "Non. Étant donné que notre moteur fonctionne entièrement localement dans votre navigateur, il n'y a pas de limites artificielles. Vous pouvez facilement <bold>convertir de gros mp3 en m4a en ligne sans téléversement serveur</bold>, limité uniquement par la RAM de votre appareil et sa puissance de traitement. C'est la <bold>meilleure solution de convertisseur audio mp3 en m4a en ligne gratuit sans limite</bold> disponible.",
        "faq3_q": "Puis-je convertir un MP3 en M4A directement sur iPhone sans télécharger d'application ?",
        "faq3_a": "Oui, vous pouvez tout à fait <bold>convertir mp3 en m4a sur iphone</bold> directement via Safari. Puisque l'outil repose sur la technologie moderne WebAssembly et l'API Web Audio, tout le processus s'exécute nativement dans votre navigateur mobile, vous évitant de télécharger des applications tierces encombrantes.",
        "faq4_q": "Pourquoi le AAC à 256kbps est-il considéré comme meilleur que le MP3 à 320kbps ?",
        "faq4_a": "Le AAC (le codec audio utilisé à l'intérieur des fichiers M4A) est un algorithme beaucoup plus récent et plus efficace que le MP3. Un fichier AAC à 256kbps conserve la clarté des hautes fréquences et les détails transitoires mieux qu'un MP3 traditionnel à 320kbps, tout en produisant généralement un fichier globalement plus petit. C'est pourquoi Apple Music utilise le AAC à 256kbps comme format d'encodage standard.",
        "faq5_q": "Mes fichiers audio sont-ils téléversés sur votre serveur pendant la conversion ?",
        "faq5_a": "Jamais. Notre architecture garantit une expérience <bold>rapide de mp3 en m4a sans téléversement</bold>. Vos fichiers restent entièrement sur votre disque dur local ou votre stockage mobile. La conversion se fait strictement côté client, assurant que vos fichiers audio personnels et votre propriété intellectuelle restent totalement privés."
    }
}

de_translations = {
    "mp3_to_m4a": {
        "meta_title": "Kostenloser MP3 zu M4A Konverter Online",
        "meta_description": "Konvertieren Sie MP3 in M4A online kostenlos mit bis zu 256kbps und 320kbps. Schnelle, clientseitige Batch-Audiokonvertierung in Ihrem Browser ohne Server-Uploads.",
        "h1": "Kostenloser <highlight>MP3 zu M4A</highlight> Konverter Online",
        "subtitle": "Konvertieren Sie MP3-Titel sofort in M4A (AAC) mithilfe fortschrittlicher WebAssembly-Technologie direkt in Ihrem Browser. Erleben Sie eine schnelle, nahtlose Konvertierung bei absolutem Datenschutz — keine Cloud-Uploads und keine Dateigrößenbeschränkungen.",
        "step_title": "Wie man MP3 in M4A in 3 einfachen Schritten konvertiert",
        "step1_title": "Audio Hochladen",
        "step1_desc": "Ziehen Sie einzelne oder mehrere MP3-Audiodateien per Drag & Drop in die sichere Konvertierungszone oben.",
        "step2_title": "Bitrate Auswählen",
        "step2_desc": "Wählen Sie Ihr gewünschtes AAC-Bitraten-Preset (128 kbps, 192 kbps, 256 kbps oder 320 kbps) für optimale Qualität.",
        "step3_title": "Konvertieren & Herunterladen",
        "step3_desc": "Klicken Sie auf Konvertieren und laden Sie einzelne M4A-Titel herunter oder exportieren Sie sie sofort als praktische ZIP-Datei.",
        "why_title": "Warum MP3 in AAC/M4A konvertieren?",
        "why_p1": "Obwohl MP3 jahrzehntelang der Standard war, ist es funktionell ein veraltetes Format. Die Konvertierung Ihrer Dateien in den M4A-Container (unter Verwendung des fortschrittlichen AAC-Codecs) bietet erhebliche technische Vorteile. AAC wurde als Nachfolger von MP3 entwickelt und bietet eine überlegene akustische Effizienz sowie eine breitere Frequenzspektrums-Beibehaltung bei kleineren Dateigrößen.",
        "why_p2": "Wenn Sie im Apple-Ökosystem verankert sind, ist dieses Format sehr zu empfehlen. M4A bietet eine nahtlose Wiedergabe auf Apple-Geräten wie iPhone, iPad, Mac und iTunes. Wenn Sie außerdem einen zuverlässigen <bold>mp3 zu m4a klingelton konverter</bold> benötigen, gewährleistet die Standardisierung Ihrer Dateien auf M4A eine perfekte Kompatibilität mit modernen mobilen Betriebssystemen.",
        "bitrate_title": "Detaillierter Bitraten- & Qualitätsratgeber",
        "bitrate_th1": "Preset Bitrate",
        "bitrate_th2": "Codec-Standard",
        "bitrate_th3": "Bester Anwendungsfall",
        "bitrate_th4": "Relative Dateigröße & Qualität",
        "bitrate_128_use": "Sprache / Podcasts",
        "bitrate_128_desc": "Kleinste Größe; akzeptable akustische Qualität für Sprache.",
        "bitrate_192_use": "Tägliches Hören",
        "bitrate_192_desc": "Ausgewogene Größe; transparente Qualität für Standard-Autolautsprecher oder einfache Kopfhörer.",
        "bitrate_256_use": "Apple Music Standard",
        "bitrate_256_desc": "Etwas größer; für die meisten Hörer praktisch nicht von der Original-CD-Quelle zu unterscheiden.",
        "bitrate_320_use": "Studio / Orchestral",
        "bitrate_320_desc": "Größte Größe; bewahrt komplexe Frequenzdetails für High-End-Akustikgeräte.",
        "features_title": "Hauptmerkmale unserer clientseitigen Audio-Engine",
        "feat1_title": "100% clientseitige Privatsphäre",
        "feat1_desc": "Es berühren niemals Audiodaten einen Remote-Server. Wenn Sie diesen <bold>mp3 zu m4a konverter online kostenlos</bold> verwenden, findet die gesamte Verarbeitung direkt in Ihrem Browser statt.",
        "feat2_title": "Stapelverarbeitung (Batch)",
        "feat2_desc": "Konvertieren Sie Dutzende von Dateien gleichzeitig ohne Server-Warteschlangenverzögerungen. Dies ist der schnellste <bold>batch mp3 zu m4a konverter online</bold>, der verfügbar ist.",
        "feat3_title": "Beibehaltene Audio-Metadaten",
        "feat3_desc": "Behält Ihre wichtigen ID3-Tags (Künstler, Album, Titel) bei, die während des Konvertierungsprozesses automatisch auf MP4-Atome abgebildet werden.",
        "feat4_title": "Keine Softwareinstallation",
        "feat4_desc": "Nahtloses <bold>konvertieren von mp3 zu aac m4a im browser</bold> über alle modernen Desktop- und mobilen Betriebssysteme nativ hinweg.",
        "faq_title": "Häufig Gestellte Fragen",
        "faq1_q": "Wie konvertiert man MP3 in M4A ohne Qualitätsverlust?",
        "faq1_a": "Um <bold>mp3 in m4a ohne verlust der klangqualität zu konvertieren</bold>, sollten Sie die ursprüngliche Bitrate Ihrer MP3-Datei anpassen oder leicht überschreiten. Wenn Ihre MP3 beispielsweise 192kbps hat, stellt die Auswahl des Presets 192kbps oder <bold>mp3 zu m4a 256kbps online</bold> sicher, dass Sie alle hörbaren akustischen Daten während des Codec-Übergangs erhalten.",
        "faq2_q": "Gibt es eine Dateigrößenbeschränkung bei der Konvertierung großer Audiodateien?",
        "faq2_a": "Nein. Da unsere Engine vollständig lokal in Ihrem Browser arbeitet, gibt es keine künstlichen Obergrenzen. Sie können problemlos <bold>große mp3 in m4a online ohne server-upload konvertieren</bold>, nur begrenzt durch den verfügbaren RAM und die Verarbeitungsleistung Ihres Geräts. Es ist die <bold>beste mp3 zu m4a audio konverter online kostenlos ohne limit</bold> Lösung auf dem Markt.",
        "faq3_q": "Kann ich MP3 direkt auf dem iPhone in M4A konvertieren, ohne eine App herunterzuladen?",
        "faq3_a": "Ja, Sie können absolut <bold>mp3 in m4a auf dem iphone konvertieren</bold>, direkt über Safari. Da das Tool auf der modernen WebAssembly- und der Web Audio API basiert, läuft der gesamte Prozess nativ in Ihrem mobilen Browser und erspart Ihnen das Herunterladen von sperrigen Drittanbieter-Anwendungen.",
        "faq4_q": "Warum wird 256kbps AAC besser als 320kbps MP3 angesehen?",
        "faq4_a": "AAC (der Audio-Codec, der in M4A-Dateien verwendet wird) ist ein viel neuerer und effizienterer Algorithmus als MP3. Eine 256kbps AAC-Datei behält Hochfrequenzklarheit und Transienten-Details besser bei als eine herkömmliche 320kbps MP3, was typischerweise zu einer kleineren Gesamtdateigröße führt. Aus diesem Grund verwendet Apple Music 256kbps AAC als Standardkodierungsformat.",
        "faq5_q": "Werden meine Audiodateien während der Konvertierung auf Ihren Server hochgeladen?",
        "faq5_a": "Niemals. Unsere Architektur garantiert eine <bold>schnelle mp3 zu m4a erfahrung ohne hochladen</bold>. Ihre Dateien verbleiben vollständig auf Ihrer lokalen Festplatte oder Ihrem mobilen Speicher. Die Konvertierung erfolgt streng clientseitig, wodurch sichergestellt wird, dass Ihre persönlichen Audio- und geistigen Eigentumsrechte vollständig privat bleiben."
    }
}

pt_translations = {
    "mp3_to_m4a": {
        "meta_title": "Conversor de MP3 para M4A Online e Gratuito",
        "meta_description": "Converta MP3 para M4A online gratuitamente a até 256kbps e 320kbps. Conversão de áudio em lote rápida e do lado do cliente no seu navegador, sem uploads para o servidor.",
        "h1": "Conversor de <highlight>MP3 para M4A</highlight> Online Grátis",
        "subtitle": "Converta faixas MP3 em M4A (AAC) instantaneamente usando tecnologia WebAssembly avançada diretamente no seu navegador. Experimente uma conversão rápida e contínua com total privacidade de dados — zero uploads para a nuvem e sem limites de tamanho de arquivo.",
        "step_title": "Como Converter MP3 para M4A em 3 Passos Simples",
        "step1_title": "Fazer Upload do Áudio",
        "step1_desc": "Arraste e solte um ou vários arquivos de áudio MP3 na zona de conversão segura acima.",
        "step2_title": "Selecionar Taxa de Bits",
        "step2_desc": "Escolha a predefinição de taxa de bits AAC desejada (128 kbps, 192 kbps, 256 kbps ou 320 kbps) para obter a qualidade ideal.",
        "step3_title": "Converter e Baixar",
        "step3_desc": "Clique em converter e baixe as faixas M4A individualmente ou exporte em lote como um prático arquivo ZIP instantaneamente.",
        "why_title": "Por que Converter MP3 para AAC/M4A?",
        "why_p1": "Embora o MP3 tenha sido o padrão por décadas, é funcionalmente um formato legado. Converter seus arquivos para o contêiner M4A (usando o codec AAC avançado) oferece vantagens técnicas significativas. O AAC foi projetado para ser o sucessor do MP3, oferecendo eficiência acústica superior e retenção mais ampla do espectro de frequências com tamanhos de arquivo menores.",
        "why_p2": "Se você está inserido no ecossistema da Apple, este formato é altamente recomendado. O M4A oferece reprodução contínua em dispositivos Apple, como iPhone, iPad, Mac e iTunes. Além disso, se você precisa de um <bold>conversor de toque mp3 para m4a</bold> confiável, padronizar seus arquivos para M4A garante compatibilidade perfeita com os sistemas operacionais móveis modernos.",
        "bitrate_title": "Guia Detalhado de Taxa de Bits e Qualidade",
        "bitrate_th1": "Predefinição de Taxa",
        "bitrate_th2": "Padrão de Codec",
        "bitrate_th3": "Melhor Caso de Uso",
        "bitrate_th4": "Tamanho Relativo do Arquivo e Qualidade",
        "bitrate_128_use": "Voz / Podcasts",
        "bitrate_128_desc": "Menor tamanho; qualidade acústica aceitável para fala.",
        "bitrate_192_use": "Audição Diária",
        "bitrate_192_desc": "Tamanho equilibrado; qualidade transparente para alto-falantes de carro padrão ou fones de ouvido casuais.",
        "bitrate_256_use": "Padrão Apple Music",
        "bitrate_256_desc": "Ligeiramente maior; praticamente indistinguível da fonte de CD original para a maioria dos ouvintes.",
        "bitrate_320_use": "Estúdio / Orquestral",
        "bitrate_320_desc": "Maior tamanho; preserva detalhes complexos de frequência para equipamentos acústicos de ponta.",
        "features_title": "Principais Recursos do Nosso Motor de Áudio no Lado do Cliente",
        "feat1_title": "Privacidade 100% no Lado do Cliente",
        "feat1_desc": "Nenhum dado de áudio toca em um servidor remoto. Ao usar este <bold>conversor mp3 para m4a online gratis</bold>, todo o processamento ocorre diretamente no seu navegador.",
        "feat2_title": "Processamento em Lote",
        "feat2_desc": "Converta dezenas de arquivos simultaneamente sem atrasos de fila do servidor. Este é o <bold>conversor em lote mp3 para m4a online</bold> mais rápido disponível.",
        "feat3_title": "Metadados de Áudio Preservados",
        "feat3_desc": "Retém suas tags ID3 essenciais (Artista, Álbum, Título) mapeadas automaticamente para átomos MP4 durante o processo de conversão.",
        "feat4_title": "Sem Instalação de Software",
        "feat4_desc": "Sem problemas, você pode <bold>converter mp3 em aac m4a no navegador</bold> em todos os sistemas operacionais modernos para desktop e dispositivos móveis nativamente.",
        "faq_title": "Perguntas Frequentes",
        "faq1_q": "Como converter MP3 para M4A sem perder a qualidade do som?",
        "faq1_a": "Para <bold>converter mp3 para m4a sem perder qualidade de som</bold>, você deve corresponder ou exceder um pouco a taxa de bits original do seu arquivo MP3. Por exemplo, se o seu MP3 for 192kbps, selecionar a predefinição de 192kbps ou <bold>mp3 para m4a 256kbps online</bold> garante a preservação de todos os dados acústicos audíveis durante a transição do codec.",
        "faq2_q": "Existe um limite de tamanho de arquivo ao converter arquivos de áudio grandes?",
        "faq2_a": "Não. Como nosso mecanismo opera de forma totalmente local dentro do seu navegador, não há limites artificiais. Você pode facilmente <bold>converter mp3 grandes para m4a online sem upload no servidor</bold>, limitado apenas pela RAM e pelo poder de processamento disponíveis no seu dispositivo. É a <bold>melhor solução conversor de áudio mp3 para m4a online grátis sem limite</bold> disponível.",
        "faq3_q": "Posso converter MP3 para M4A diretamente no iPhone sem baixar um aplicativo?",
        "faq3_a": "Sim, você pode perfeitamente <bold>converter mp3 para m4a no iphone</bold> diretamente pelo Safari. Como a ferramenta depende do WebAssembly moderno e da API de Áudio da Web, todo o processo é executado nativamente no seu navegador móvel, evitando o download de aplicativos de terceiros pesados.",
        "faq4_q": "Por que o AAC a 256 kbps é considerado melhor do que o MP3 a 320 kbps?",
        "faq4_a": "AAC (o codec de áudio usado em arquivos M4A) é um algoritmo muito mais novo e eficiente do que o MP3. Um arquivo AAC de 256 kbps retém a clareza de alta frequência e os detalhes transitórios melhor do que um MP3 antigo de 320 kbps, resultando normalmente em um tamanho geral de arquivo menor. É por isso que o Apple Music usa o AAC de 256 kbps como seu formato de codificação padrão.",
        "faq5_q": "Meus arquivos de áudio são enviados para o seu servidor durante a conversão?",
        "faq5_a": "Nunca. Nossa arquitetura garante uma experiência <bold>rápida de mp3 para m4a sem uploads</bold>. Seus arquivos permanecem inteiramente em seu disco rígido local ou armazenamento móvel. A conversão acontece estritamente no lado do cliente, garantindo que seu áudio pessoal e propriedade intelectual sejam totalmente privados."
    }
}

all_trans = {
    "en": en_translations,
    "es": es_translations,
    "fr": fr_translations,
    "de": de_translations,
    "pt": pt_translations
}

for lang, data in all_trans.items():
    filepath = f"messages/{lang}.json"
    with open(filepath, "r", encoding="utf-8") as f:
        content = json.load(f)
    
    content.update(data)
    
    with open(filepath, "w", encoding="utf-8") as f:
        json.dump(content, f, indent=2, ensure_ascii=False)

print("Translation dictionaries injected!")
