const fs = require('fs');
const path = require('path');

const locales = ['en', 'es', 'fr', 'de', 'pt'];

const translations = {
  en: {
    mv_seo_h2_how: "How Our Audio Metadata Viewer Online Works",
    mv_seo_step1_title: "1. Drop Your File",
    mv_seo_step1_desc: "Select or drag & drop any audio container (MP3, WAV, FLAC, M4A) directly into the inspection zone to act as an advanced wav file header reader online.",
    mv_seo_step2_title: "2. Local Browser Decoding",
    mv_seo_step2_desc: "Our secure WebAssembly/JS engine intercepts the file memory locally. This is a true online mediainfo alternative without uploading your file.",
    mv_seo_step3_title: "3. Instant Deep Analysis",
    mv_seo_step3_desc: "Instantly view low level audio codec properties in browser, stream dispositions, and standard ID3 tags in one unified dashboard.",
    mv_seo_h2_cap: "Comprehensive Data Extraction Capabilities",
    mv_seo_cap_desc: "Use our powerful audio stream inspector online to check audio codec online and extract exact structural knowledge. Here is the exact data our inspector parses:",
    mv_seo_cap1_title: "1. File Integrity & Basic Container",
    mv_seo_cap1_i1_str: "Checksums:",
    mv_seo_cap1_i1_txt: " Serve as an mp3 checksum generator online for MD5 & SHA hash verification.",
    mv_seo_cap1_i2_str: "File Properties:",
    mv_seo_cap1_i2_txt: " File Name, Size, File Type.",
    mv_seo_cap1_i3_str: "Headers:",
    mv_seo_cap1_i3_txt: " MIME Type & verified Extension.",
    mv_seo_cap2_title: "2. Audio Stream & Encoding Properties",
    mv_seo_cap2_i1_str: "Architecture:",
    mv_seo_cap2_i1_txt: " MPEG Audio Version & Layer.",
    mv_seo_cap2_i2_str: "Codec Details:",
    mv_seo_cap2_i2_txt: " Codec Name, Long Name, & Tag String. Utilize it as a flac metadata and codec viewer.",
    mv_seo_cap2_i3_str: "Format & Streams:",
    mv_seo_cap2_i3_txt: " Format Long Name, Probe Score, Nb Streams/Programs.",
    mv_seo_cap3_title: "3. Technical Audio Quality Parameters",
    mv_seo_cap3_i1_str: "Resolution:",
    mv_seo_cap3_i1_txt: " Check sample rate of audio online (Hz), Sample Format (e.g., fltp).",
    mv_seo_cap3_i2_str: "Bitrate:",
    mv_seo_cap3_i2_txt: " Act as an audio bitrate checker online to see True Bitrate (bps & kbps).",
    mv_seo_cap3_i3_str: "Spatial:",
    mv_seo_cap3_i3_txt: " Channel Mode, Channels count, Channel Layout.",
    mv_seo_cap4_title: "4. Advanced Codec & Stream Properties",
    mv_seo_cap4_i1_str: "Modes:",
    mv_seo_cap4_i1_txt: " MS Stereo / Intensity Stereo status.",
    mv_seo_cap4_i2_str: "Timestamps:",
    mv_seo_cap4_i2_txt: " Time Base, Start PTS, Duration (Timestamp & human-readable).",
    mv_seo_cap4_i3_str: "Technical Flags:",
    mv_seo_cap4_i3_txt: " Copyright, Original Media, Emphasis, ID3 Size, Initial Padding, Frame Rates.",
    mv_seo_cap4_i4_str: "Cataloging:",
    mv_seo_cap4_i4_txt: " Year, Genre, Track Index, Cover Art extraction.",
    mv_seo_h2_why: "Why Deep Audio Inspection Matters",
    mv_seo_why1_title: "Audio Mastering Quality Checks",
    mv_seo_why1_desc: "Ensure your final bounces retain integrity. Want to know <howto>how to check true bitrate of mp3 online</howto>? Verify true bitrates, confirm sample formats, and check codec string names to avoid silent down-sampling.",
    mv_seo_why2_title: "Podcast & Streaming Compliance",
    mv_seo_why2_desc: "Spotify and Apple Podcasts require strict encoding standards. Validate stereo channel modes, inspect exact duration timestamps, and ensure required ID3 cover tags and disposition flags are securely embedded before publishing.",
    mv_seo_why3_title: "Forensic Analysis & File Integrity",
    mv_seo_why3_desc: "Uncover origin traces without compromising file privacy. Act as a <free>free audio file checksum and integrity checker</free> to audit stream headers, validate hashes, and expose hidden padding packed inside suspicious containers.",
    mv_seo_h2_adv: "The Inspection Advantage",
    mv_seo_adv_th1: "Feature Capability",
    mv_seo_adv_th2: "Basic Online Tag Readers",
    mv_seo_adv_th3: "Our Deep Stream Inspector",
    mv_seo_adv_r1c1: "Standard ID3 (Title, Artist)",
    mv_seo_adv_r2c1: "Data Privacy & Security",
    mv_seo_adv_r2c2: "Server uploads required",
    mv_seo_adv_r2c3: "100% Client-Side Local Execution",
    mv_seo_adv_r3c1: "Hash Checksums (MD5/SHA)",
    mv_seo_adv_r3c2: "Missing",
    mv_seo_adv_r4c1: "True Bitrate & Sample Formats",
    mv_seo_adv_r4c2: "Often estimates",
    mv_seo_adv_r4c3: "Exact Decoder Probe Data",
    mv_seo_adv_r5c1: "Stream Dispositions & Flags",
    mv_seo_adv_r5c2: "Missing",
    mv_seo_adv_r5c3: "Full Accessibility & Codec Flags",
    mv_seo_adv_r6c1: "Advanced Codec Timestamps (PTS)",
    mv_seo_adv_r6c2: "Missing",
    mv_seo_h2_faq: "Frequently Asked Questions",
    mv_seo_faq1_q: "Are my pre-release audio files safe?",
    mv_seo_faq1_a: "Absolutely. This tool utilizes modern browser APIs and WebAssembly to parse file binaries directly in your device's memory. <no>No audio files are ever uploaded to any server.</no> You can even disconnect your internet after loading the page and the inspector will continue to function.",
    mv_seo_faq2_q: "What is the difference between ID3 tags and stream properties?",
    mv_seo_faq2_a: "<id3>ID3 tags</id3> are user-editable metadata (like Artist, Title, and Album Art) appended to the file. <stream>Stream properties</stream> (like True Bitrate, Sample Format, and Codec Tags) are the uneditable, raw mathematical instructions that tell hardware how to decode and play the audio. Our tool exposes both to seamlessly <inspect>inspect audio file stream tags and sample format</inspect>.",
    mv_seo_faq3_q: "How does deep codec probing work locally without installing software?",
    mv_seo_faq3_a: "Historically, deep probing required command-line tools like FFprobe. As a full <online>online ffprobe tool</online>, we leverage <wasm>WebAssembly (Wasm)</wasm> and high-performance JavaScript engines to execute complex binary parsing logic entirely inside your browser's secure sandbox, offering desktop-grade inspection instantly.",
    mv_seo_faq4_q: "Can I detect upsampled or fake high-res audio?",
    mv_seo_faq4_a: "Yes. By comparing the declared ID3 bitrate against the <true>True Bitrate</true> and <sample>Sample Format (e.g., fltp)</sample> extracted from the codec stream, audio professionals can identify discrepancies indicative of artificially inflated or re-encoded files."
  },
  de: {
    mv_seo_h2_how: "Wie unser Online-Audio-Metadaten-Viewer funktioniert",
    mv_seo_step1_title: "1. Datei ablegen",
    mv_seo_step1_desc: "Wählen oder ziehen Sie einen Audio-Container (MP3, WAV, FLAC, M4A) direkt in den Inspektionsbereich, um als erweiterter WAV-Header-Leser online zu fungieren.",
    mv_seo_step2_title: "2. Lokale Browser-Dekodierung",
    mv_seo_step2_desc: "Unsere sichere WebAssembly/JS-Engine liest den Dateispeicher lokal. Dies ist eine echte MediaInfo-Alternative online, ohne Ihre Datei hochzuladen.",
    mv_seo_step3_title: "3. Sofortige Tiefenanalyse",
    mv_seo_step3_desc: "Sehen Sie sich sofort Low-Level-Audio-Codec-Eigenschaften, Stream-Dispositionen und Standard-ID3-Tags in einem übersichtlichen Dashboard an.",
    mv_seo_h2_cap: "Umfassende Datenextraktionsfunktionen",
    mv_seo_cap_desc: "Verwenden Sie unseren leistungsstarken Audio-Stream-Inspektor online, um Audio-Codecs online zu überprüfen und genaue Strukturdaten zu extrahieren. Hier ist genau, was wir parsen:",
    mv_seo_cap1_title: "1. Dateiintegrität & Basis-Container",
    mv_seo_cap1_i1_str: "Prüfsummen:",
    mv_seo_cap1_i1_txt: " Fungiert als Online-MP3-Prüfsummengenerator für MD5- & SHA-Hash-Überprüfungen.",
    mv_seo_cap1_i2_str: "Dateieigenschaften:",
    mv_seo_cap1_i2_txt: " Dateiname, Größe, Dateityp.",
    mv_seo_cap1_i3_str: "Header:",
    mv_seo_cap1_i3_txt: " MIME-Typ & überprüfte Erweiterung.",
    mv_seo_cap2_title: "2. Audio-Stream & Kodierungseigenschaften",
    mv_seo_cap2_i1_str: "Architektur:",
    mv_seo_cap2_i1_txt: " MPEG-Audio-Version & Layer.",
    mv_seo_cap2_i2_str: "Codec-Details:",
    mv_seo_cap2_i2_txt: " Codec-Name, langer Name & Tag-String. Nutzen Sie es als FLAC-Metadaten- und Codec-Viewer.",
    mv_seo_cap2_i3_str: "Format & Streams:",
    mv_seo_cap2_i3_txt: " Formats langer Name, Probe-Score, Anzahl der Streams/Programme.",
    mv_seo_cap3_title: "3. Technische Audio-Qualitätsparameter",
    mv_seo_cap3_i1_str: "Auflösung:",
    mv_seo_cap3_i1_txt: " Überprüfen Sie die Audio-Samplerate online (Hz), das Sample-Format (z.B. fltp).",
    mv_seo_cap3_i2_str: "Bitrate:",
    mv_seo_cap3_i2_txt: " Fungiert als Audio-Bitraten-Checker online, um die wahre Bitrate (bps & kbps) zu sehen.",
    mv_seo_cap3_i3_str: "Räumlich:",
    mv_seo_cap3_i3_txt: " Kanalmodus, Kanalanzahl, Kanal-Layout.",
    mv_seo_cap4_title: "4. Erweiterte Codec- & Stream-Eigenschaften",
    mv_seo_cap4_i1_str: "Modi:",
    mv_seo_cap4_i1_txt: " MS-Stereo- / Intensity-Stereo-Status.",
    mv_seo_cap4_i2_str: "Zeitstempel:",
    mv_seo_cap4_i2_txt: " Zeitbasis, Start-PTS, Dauer (Zeitstempel & menschenlesbar).",
    mv_seo_cap4_i3_str: "Technische Flags:",
    mv_seo_cap4_i3_txt: " Urheberrecht, Originalmedien, Betonung, ID3-Größe, Anfangspolsterung, Bildraten.",
    mv_seo_cap4_i4_str: "Katalogisierung:",
    mv_seo_cap4_i4_txt: " Jahr, Genre, Track-Index, Coverbild-Extraktion.",
    mv_seo_h2_why: "Warum tiefe Audio-Inspektion wichtig ist",
    mv_seo_why1_title: "Qualitätsprüfungen beim Audio-Mastering",
    mv_seo_why1_desc: "Stellen Sie sicher, dass Ihre finalen Bounces die Integrität behalten. Möchten Sie wissen, <howto>wie man die wahre Bitrate von MP3s online überprüft</howto>? Bestätigen Sie wahre Bitraten, Sample-Formate und Codec-String-Namen, um leises Downsampling zu vermeiden.",
    mv_seo_why2_title: "Podcast & Streaming-Konformität",
    mv_seo_why2_desc: "Spotify und Apple Podcasts erfordern strenge Kodierungsstandards. Überprüfen Sie Stereo-Kanalmodi, inspizieren Sie exakte Zeitstempel und stellen Sie sicher, dass ID3-Cover-Tags sicher eingebettet sind.",
    mv_seo_why3_title: "Forensische Analyse & Dateiintegrität",
    mv_seo_why3_desc: "Decken Sie Ursprungsspuren auf, ohne den Dateidatenschutz zu gefährden. Agieren Sie als <free>kostenloser Audio-Prüfsummen- und Integritätsprüfer</free>, um Stream-Header zu prüfen, Hashes zu validieren und verborgenes Padding zu enttarnen.",
    mv_seo_h2_adv: "Der Inspektionsvorteil",
    mv_seo_adv_th1: "Feature-Fähigkeit",
    mv_seo_adv_th2: "Basis-Online-Tag-Reader",
    mv_seo_adv_th3: "Unser tiefer Stream-Inspektor",
    mv_seo_adv_r1c1: "Standard-ID3 (Titel, Künstler)",
    mv_seo_adv_r2c1: "Datenschutz & Sicherheit",
    mv_seo_adv_r2c2: "Server-Uploads erforderlich",
    mv_seo_adv_r2c3: "100% Client-Side Lokale Ausführung",
    mv_seo_adv_r3c1: "Hash-Prüfsummen (MD5/SHA)",
    mv_seo_adv_r3c2: "Fehlt",
    mv_seo_adv_r4c1: "Wahre Bitrate & Sample-Formate",
    mv_seo_adv_r4c2: "Oft Schätzungen",
    mv_seo_adv_r4c3: "Exakte Decoder-Sondendaten",
    mv_seo_adv_r5c1: "Stream-Dispositionen & Flags",
    mv_seo_adv_r5c2: "Fehlt",
    mv_seo_adv_r5c3: "Volle Zugänglichkeit & Codec-Flags",
    mv_seo_adv_r6c1: "Erweiterte Codec-Zeitstempel (PTS)",
    mv_seo_adv_r6c2: "Fehlt",
    mv_seo_h2_faq: "Häufig gestellte Fragen",
    mv_seo_faq1_q: "Sind meine Vorab-Audio-Dateien sicher?",
    mv_seo_faq1_a: "Absolut. Dieses Tool nutzt moderne Browser-APIs und WebAssembly, um Dateibinärdaten direkt im Speicher Ihres Geräts zu analysieren. <no>Keine Audio-Dateien werden jemals auf einen Server hochgeladen.</no> Sie können sogar nach dem Laden der Seite das Internet trennen.",
    mv_seo_faq2_q: "Was ist der Unterschied zwischen ID3-Tags und Stream-Eigenschaften?",
    mv_seo_faq2_a: "<id3>ID3-Tags</id3> sind vom Benutzer bearbeitbare Metadaten, die an die Datei angehängt sind. <stream>Stream-Eigenschaften</stream> sind die unveränderbaren, rohen mathematischen Anweisungen, die der Hardware mitteilen, wie das Audio dekodiert wird. Unser Tool legt beides offen, um nahtlos <inspect>Audio-Datei-Stream-Tags und das Sample-Format zu inspizieren</inspect>.",
    mv_seo_faq3_q: "Wie funktioniert tiefes Codec-Probing lokal ohne Installation von Software?",
    mv_seo_faq3_a: "In der Vergangenheit erforderte tiefes Probing Tools wie FFprobe. Als vollständiges <online>Online-FFprobe-Tool</online> nutzen wir <wasm>WebAssembly (Wasm)</wasm>, um die Parsing-Logik sicher im Browser auszuführen und sofort Desktop-Qualität zu liefern.",
    mv_seo_faq4_q: "Kann ich hochskaliertes oder gefälschtes High-Res-Audio erkennen?",
    mv_seo_faq4_a: "Ja. Durch den Vergleich der deklarierten ID3-Bitrate mit der <true>Wahren Bitrate</true> und dem <sample>Sample-Format</sample>, die aus dem Codec-Stream extrahiert wurden, können Profis Unstimmigkeiten bei künstlich aufgeblähten Dateien erkennen."
  },
  es: {
    mv_seo_h2_how: "Cómo funciona nuestro visor de metadatos de audio en línea",
    mv_seo_step1_title: "1. Suelte su archivo",
    mv_seo_step1_desc: "Seleccione o arrastre y suelte cualquier contenedor de audio (MP3, WAV, FLAC, M4A) directamente en la zona de inspección para que actúe como un lector avanzado de encabezados WAV en línea.",
    mv_seo_step2_title: "2. Decodificación local en el navegador",
    mv_seo_step2_desc: "Nuestro motor seguro WebAssembly/JS intercepta la memoria del archivo localmente. Es una verdadera alternativa en línea a mediainfo sin subir su archivo.",
    mv_seo_step3_title: "3. Análisis profundo al instante",
    mv_seo_step3_desc: "Vea instantáneamente las propiedades del códec de audio a bajo nivel, disposiciones del flujo y etiquetas ID3 estándar en un panel unificado.",
    mv_seo_h2_cap: "Capacidades de extracción de datos completas",
    mv_seo_cap_desc: "Utilice nuestro potente inspector de flujo de audio en línea para verificar el códec y extraer el conocimiento estructural exacto. Aquí están los datos:",
    mv_seo_cap1_title: "1. Integridad del archivo y contenedor básico",
    mv_seo_cap1_i1_str: "Sumas de comprobación:",
    mv_seo_cap1_i1_txt: " Sirve como generador en línea de sumas de comprobación MP3 para la verificación de hash MD5 y SHA.",
    mv_seo_cap1_i2_str: "Propiedades del archivo:",
    mv_seo_cap1_i2_txt: " Nombre de archivo, tamaño, tipo de archivo.",
    mv_seo_cap1_i3_str: "Encabezados:",
    mv_seo_cap1_i3_txt: " Tipo MIME y extensión verificada.",
    mv_seo_cap2_title: "2. Flujo de audio y propiedades de codificación",
    mv_seo_cap2_i1_str: "Arquitectura:",
    mv_seo_cap2_i1_txt: " Versión de audio MPEG y capa.",
    mv_seo_cap2_i2_str: "Detalles del códec:",
    mv_seo_cap2_i2_txt: " Nombre del códec, nombre largo y cadena de etiquetas. Utilícelo como un visor de códecs y metadatos FLAC.",
    mv_seo_cap2_i3_str: "Formato y flujos:",
    mv_seo_cap2_i3_txt: " Nombre largo del formato, puntuación de sondeo, número de flujos/programas.",
    mv_seo_cap3_title: "3. Parámetros técnicos de calidad de audio",
    mv_seo_cap3_i1_str: "Resolución:",
    mv_seo_cap3_i1_txt: " Verifique la frecuencia de muestreo del audio en línea (Hz), formato de muestra (p. ej., fltp).",
    mv_seo_cap3_i2_str: "Tasa de bits:",
    mv_seo_cap3_i2_txt: " Actúe como verificador de tasa de bits de audio para ver la tasa de bits verdadera (bps y kbps).",
    mv_seo_cap3_i3_str: "Espacial:",
    mv_seo_cap3_i3_txt: " Modo de canal, recuento de canales, diseño de canales.",
    mv_seo_cap4_title: "4. Propiedades avanzadas del códec y flujo",
    mv_seo_cap4_i1_str: "Modos:",
    mv_seo_cap4_i1_txt: " Estado MS Stereo / Intensity Stereo.",
    mv_seo_cap4_i2_str: "Marcas de tiempo:",
    mv_seo_cap4_i2_txt: " Base de tiempo, PTS de inicio, duración (marca de tiempo y legible).",
    mv_seo_cap4_i3_str: "Indicadores técnicos:",
    mv_seo_cap4_i3_txt: " Derechos de autor, medio original, énfasis, tamaño de ID3, relleno inicial, velocidades de fotogramas.",
    mv_seo_cap4_i4_str: "Catalogación:",
    mv_seo_cap4_i4_txt: " Año, género, índice de pista, extracción de portada.",
    mv_seo_h2_why: "Por qué es importante la inspección de audio profunda",
    mv_seo_why1_title: "Controles de calidad de masterización de audio",
    mv_seo_why1_desc: "Asegúrese de que sus exportaciones finales conserven la integridad. ¿Quiere saber <howto>cómo comprobar la verdadera tasa de bits de mp3 en línea</howto>? Verifique tasas de bits, formatos y nombres para evitar submuestreos silenciosos.",
    mv_seo_why2_title: "Cumplimiento de podcasts y transmisión",
    mv_seo_why2_desc: "Spotify y Apple Podcasts requieren estándares estrictos. Valide modos de canales estéreo, inspeccione marcas de tiempo y asegúrese de que las etiquetas ID3 necesarias estén integradas de forma segura.",
    mv_seo_why3_title: "Análisis forense e integridad de archivos",
    mv_seo_why3_desc: "Descubra rastros de origen sin comprometer la privacidad. Actúe como un <free>verificador gratuito de suma de comprobación e integridad</free> para auditar encabezados de flujo, validar hashes y exponer relleno oculto.",
    mv_seo_h2_adv: "La ventaja de la inspección",
    mv_seo_adv_th1: "Capacidad de característica",
    mv_seo_adv_th2: "Lectores de etiquetas en línea básicos",
    mv_seo_adv_th3: "Nuestro inspector de flujo profundo",
    mv_seo_adv_r1c1: "ID3 estándar (título, artista)",
    mv_seo_adv_r2c1: "Privacidad y seguridad de los datos",
    mv_seo_adv_r2c2: "Requiere subidas al servidor",
    mv_seo_adv_r2c3: "Ejecución local 100% del lado del cliente",
    mv_seo_adv_r3c1: "Sumas de comprobación (MD5/SHA)",
    mv_seo_adv_r3c2: "Falta",
    mv_seo_adv_r4c1: "Verdadera tasa de bits y formatos",
    mv_seo_adv_r4c2: "A menudo estimaciones",
    mv_seo_adv_r4c3: "Datos exactos de sondeo de decodificador",
    mv_seo_adv_r5c1: "Disposiciones e indicadores de flujo",
    mv_seo_adv_r5c2: "Falta",
    mv_seo_adv_r5c3: "Accesibilidad completa e indicadores de códec",
    mv_seo_adv_r6c1: "Marcas de tiempo avanzadas de códec (PTS)",
    mv_seo_adv_r6c2: "Falta",
    mv_seo_h2_faq: "Preguntas frecuentes",
    mv_seo_faq1_q: "¿Están seguros mis archivos de audio previos al lanzamiento?",
    mv_seo_faq1_a: "Absolutamente. Esta herramienta utiliza WebAssembly para analizar archivos binarios directamente en la memoria de su dispositivo. <no>Ningún archivo de audio se sube a ningún servidor.</no> Incluso puede desconectarse de Internet después de cargar la página.",
    mv_seo_faq2_q: "¿Cuál es la diferencia entre las etiquetas ID3 y las propiedades del flujo?",
    mv_seo_faq2_a: "<id3>Las etiquetas ID3</id3> son metadatos editables añadidos al archivo. <stream>Las propiedades del flujo</stream> son instrucciones matemáticas sin procesar que indican al hardware cómo decodificar el audio. Nuestra herramienta expone ambos para <inspect>inspeccionar sin problemas etiquetas de flujo y el formato de muestra</inspect>.",
    mv_seo_faq3_q: "¿Cómo funciona el sondeo de códec profundo localmente sin instalar software?",
    mv_seo_faq3_a: "Históricamente requería herramientas como FFprobe. Como una completa <online>herramienta FFprobe en línea</online>, aprovechamos <wasm>WebAssembly</wasm> para ejecutar la lógica de análisis binario de forma segura, ofreciendo inspección instantánea.",
    mv_seo_faq4_q: "¿Puedo detectar audio de alta resolución falso o escalado?",
    mv_seo_faq4_a: "Sí. Al comparar la tasa de bits ID3 declarada con la <true>tasa de bits verdadera</true> y el <sample>formato de muestra</sample> extraídos, los profesionales pueden identificar discrepancias en archivos inflados artificialmente."
  },
  fr: {
    mv_seo_h2_how: "Comment fonctionne notre visionneuse de métadonnées audio en ligne",
    mv_seo_step1_title: "1. Déposez votre fichier",
    mv_seo_step1_desc: "Sélectionnez ou glissez-déposez n'importe quel conteneur audio (MP3, WAV, FLAC, M4A) directement dans la zone d'inspection pour faire office de lecteur d'en-tête de fichier wav avancé en ligne.",
    mv_seo_step2_title: "2. Décodage local dans le navigateur",
    mv_seo_step2_desc: "Notre moteur WebAssembly/JS intercepte la mémoire du fichier localement. Il s'agit d'une véritable alternative en ligne à MediaInfo, sans télécharger votre fichier.",
    mv_seo_step3_title: "3. Analyse approfondie instantanée",
    mv_seo_step3_desc: "Affichez instantanément les propriétés de bas niveau du codec audio, les dispositions du flux et les balises ID3 standard dans un tableau de bord unifié.",
    mv_seo_h2_cap: "Capacités complètes d'extraction de données",
    mv_seo_cap_desc: "Utilisez notre puissant inspecteur de flux audio en ligne pour vérifier les codecs et extraire les données structurelles. Voici les données extraites:",
    mv_seo_cap1_title: "1. Intégrité du fichier & Conteneur de base",
    mv_seo_cap1_i1_str: "Sommes de contrôle:",
    mv_seo_cap1_i1_txt: " Agit comme un générateur de somme de contrôle MP3 en ligne pour les vérifications de hachage MD5 et SHA.",
    mv_seo_cap1_i2_str: "Propriétés du fichier:",
    mv_seo_cap1_i2_txt: " Nom du fichier, Taille, Type de fichier.",
    mv_seo_cap1_i3_str: "En-têtes:",
    mv_seo_cap1_i3_txt: " Type MIME & Extension vérifiée.",
    mv_seo_cap2_title: "2. Flux audio & Propriétés d'encodage",
    mv_seo_cap2_i1_str: "Architecture:",
    mv_seo_cap2_i1_txt: " Version audio MPEG & Couche.",
    mv_seo_cap2_i2_str: "Détails du codec:",
    mv_seo_cap2_i2_txt: " Nom du codec, Nom long, & Chaîne de balises. Utilisez-le comme visionneuse de codecs FLAC.",
    mv_seo_cap2_i3_str: "Format & Flux:",
    mv_seo_cap2_i3_txt: " Nom long du format, Score de sondage, Nombre de flux/programmes.",
    mv_seo_cap3_title: "3. Paramètres techniques de qualité audio",
    mv_seo_cap3_i1_str: "Résolution:",
    mv_seo_cap3_i1_txt: " Vérifiez le taux d'échantillonnage de l'audio en ligne (Hz), Format d'échantillon (ex: fltp).",
    mv_seo_cap3_i2_str: "Débit binaire:",
    mv_seo_cap3_i2_txt: " Agit comme un vérificateur de débit audio pour voir le débit binaire réel (bps & kbps).",
    mv_seo_cap3_i3_str: "Spatial:",
    mv_seo_cap3_i3_txt: " Mode de canal, Nombre de canaux, Disposition des canaux.",
    mv_seo_cap4_title: "4. Codec avancé & Propriétés de flux",
    mv_seo_cap4_i1_str: "Modes:",
    mv_seo_cap4_i1_txt: " Statut MS Stereo / Intensity Stereo.",
    mv_seo_cap4_i2_str: "Horodatages:",
    mv_seo_cap4_i2_txt: " Base de temps, PTS de début, Durée (Horodatage & lisible par l'homme).",
    mv_seo_cap4_i3_str: "Indicateurs techniques:",
    mv_seo_cap4_i3_txt: " Droits d'auteur, Médias originaux, Emphase, Taille ID3, Remplissage initial, Fréquences d'images.",
    mv_seo_cap4_i4_str: "Catalogage:",
    mv_seo_cap4_i4_txt: " Année, Genre, Index de piste, Extraction de pochette.",
    mv_seo_h2_why: "Pourquoi l'inspection audio approfondie est importante",
    mv_seo_why1_title: "Contrôles de qualité du mastering audio",
    mv_seo_why1_desc: "Assurez-vous que vos exports finaux conservent leur intégrité. Vous voulez savoir <howto>comment vérifier le débit binaire réel des MP3 en ligne</howto>? Vérifiez les débits réels et les formats d'échantillon pour éviter les sous-échantillonnages silencieux.",
    mv_seo_why2_title: "Conformité des podcasts et du streaming",
    mv_seo_why2_desc: "Spotify et Apple Podcasts exigent des normes strictes. Validez les modes de canaux stéréo, inspectez les horodatages de durée exacts et assurez-vous que les balises ID3 requises sont intégrées en toute sécurité.",
    mv_seo_why3_title: "Analyse médico-légale & Intégrité des fichiers",
    mv_seo_why3_desc: "Découvrez les traces d'origine sans compromettre la confidentialité. Agit comme un <free>vérificateur gratuit d'intégrité de fichiers audio</free> pour valider les hachages et exposer les remplissages cachés.",
    mv_seo_h2_adv: "L'avantage de l'inspection",
    mv_seo_adv_th1: "Capacité de fonctionnalité",
    mv_seo_adv_th2: "Lecteurs de balises de base",
    mv_seo_adv_th3: "Notre inspecteur de flux profond",
    mv_seo_adv_r1c1: "ID3 standard (Titre, Artiste)",
    mv_seo_adv_r2c1: "Confidentialité & Sécurité des données",
    mv_seo_adv_r2c2: "Téléchargements sur serveur requis",
    mv_seo_adv_r2c3: "Exécution locale 100% côté client",
    mv_seo_adv_r3c1: "Sommes de contrôle (MD5/SHA)",
    mv_seo_adv_r3c2: "Manquant",
    mv_seo_adv_r4c1: "Débit binaire réel & Formats",
    mv_seo_adv_r4c2: "Souvent des estimations",
    mv_seo_adv_r4c3: "Données exactes de sonde de décodeur",
    mv_seo_adv_r5c1: "Dispositions & Indicateurs de flux",
    mv_seo_adv_r5c2: "Manquant",
    mv_seo_adv_r5c3: "Accessibilité complète & Indicateurs de codec",
    mv_seo_adv_r6c1: "Horodatages avancés du codec (PTS)",
    mv_seo_adv_r6c2: "Manquant",
    mv_seo_h2_faq: "Questions fréquemment posées",
    mv_seo_faq1_q: "Mes fichiers audio avant publication sont-ils en sécurité?",
    mv_seo_faq1_a: "Absolument. Cet outil utilise WebAssembly pour analyser les binaires de fichiers directement dans la mémoire de votre appareil. <no>Aucun fichier audio n'est jamais téléchargé sur un serveur.</no> Vous pouvez même vous déconnecter d'Internet après le chargement de la page.",
    mv_seo_faq2_q: "Quelle est la différence entre les balises ID3 et les propriétés du flux?",
    mv_seo_faq2_a: "<id3>Les balises ID3</id3> sont des métadonnées modifiables par l'utilisateur. <stream>Les propriétés du flux</stream> sont les instructions mathématiques brutes non modifiables. Notre outil expose les deux pour <inspect>inspecter en toute fluidité les balises de flux de fichiers audio</inspect>.",
    mv_seo_faq3_q: "Comment fonctionne le sondage profond de codec localement sans installer de logiciel?",
    mv_seo_faq3_a: "Historiquement, le sondage profond nécessitait des outils en ligne de commande comme FFprobe. En tant qu'outil <online>FFprobe en ligne complet</online>, nous exploitons <wasm>WebAssembly (Wasm)</wasm> pour exécuter une logique complexe en toute sécurité dans le navigateur.",
    mv_seo_faq4_q: "Puis-je détecter un son haute résolution artificiellement mis à l'échelle?",
    mv_seo_faq4_a: "Oui. En comparant le débit binaire ID3 déclaré au <true>Débit binaire réel</true> et au <sample>Format d'échantillon</sample> extraits du flux de codec, les professionnels peuvent identifier les écarts."
  },
  pt: {
    mv_seo_h2_how: "Como funciona nosso visualizador de metadados de áudio online",
    mv_seo_step1_title: "1. Solte seu arquivo",
    mv_seo_step1_desc: "Selecione ou arraste qualquer contêiner de áudio (MP3, WAV, FLAC, M4A) diretamente para a zona de inspeção para atuar como um leitor de cabeçalho wav avançado online.",
    mv_seo_step2_title: "2. Decodificação local do navegador",
    mv_seo_step2_desc: "Nosso motor WebAssembly/JS intercepta a memória do arquivo localmente. É uma verdadeira alternativa ao mediainfo online, sem fazer upload do seu arquivo.",
    mv_seo_step3_title: "3. Análise Profunda Instantânea",
    mv_seo_step3_desc: "Visualize instantaneamente propriedades de baixo nível do codec de áudio, disposições de stream e tags ID3 padrão em um painel unificado.",
    mv_seo_h2_cap: "Capacidades abrangentes de extração de dados",
    mv_seo_cap_desc: "Use nosso poderoso inspetor de fluxo de áudio online para verificar o codec e extrair o conhecimento estrutural exato. Aqui estão os dados exatos que analisamos:",
    mv_seo_cap1_title: "1. Integridade do arquivo e contêiner básico",
    mv_seo_cap1_i1_str: "Checksums:",
    mv_seo_cap1_i1_txt: " Atua como um gerador de checksum MP3 online para verificação de hash MD5 e SHA.",
    mv_seo_cap1_i2_str: "Propriedades do arquivo:",
    mv_seo_cap1_i2_txt: " Nome do arquivo, Tamanho, Tipo de arquivo.",
    mv_seo_cap1_i3_str: "Cabeçalhos:",
    mv_seo_cap1_i3_txt: " Tipo MIME e Extensão verificada.",
    mv_seo_cap2_title: "2. Stream de áudio e propriedades de codificação",
    mv_seo_cap2_i1_str: "Arquitetura:",
    mv_seo_cap2_i1_txt: " Versão e camada de áudio MPEG.",
    mv_seo_cap2_i2_str: "Detalhes do codec:",
    mv_seo_cap2_i2_txt: " Nome do codec, Nome longo e String de tag. Utilize como um visualizador de codecs e metadatos FLAC.",
    mv_seo_cap2_i3_str: "Formato e Streams:",
    mv_seo_cap2_i3_txt: " Nome longo do formato, Pontuação de sondagem, Número de streams/programas.",
    mv_seo_cap3_title: "3. Parâmetros técnicos de qualidade de áudio",
    mv_seo_cap3_i1_str: "Resolução:",
    mv_seo_cap3_i1_txt: " Verifique a taxa de amostragem de áudio online (Hz), Formato de amostra (ex: fltp).",
    mv_seo_cap3_i2_str: "Taxa de bits (Bitrate):",
    mv_seo_cap3_i2_txt: " Atua como verificador de taxa de bits para ver a Taxa de Bits Verdadeira (bps e kbps).",
    mv_seo_cap3_i3_str: "Espacial:",
    mv_seo_cap3_i3_txt: " Modo de canal, Contagem de canais, Layout do canal.",
    mv_seo_cap4_title: "4. Propriedades avançadas de codec e stream",
    mv_seo_cap4_i1_str: "Modos:",
    mv_seo_cap4_i1_txt: " Status MS Stereo / Intensity Stereo.",
    mv_seo_cap4_i2_str: "Timestamps:",
    mv_seo_cap4_i2_txt: " Base de tempo, PTS de início, Duração (Timestamp e legível).",
    mv_seo_cap4_i3_str: "Sinalizadores técnicos (Flags):",
    mv_seo_cap4_i3_txt: " Direitos autorais, Mídia original, Ênfase, Tamanho ID3, Preenchimento inicial, Taxas de quadros.",
    mv_seo_cap4_i4_str: "Catalogação:",
    mv_seo_cap4_i4_txt: " Ano, Gênero, Índice da faixa, Extração da capa.",
    mv_seo_h2_why: "Por que a inspeção profunda de áudio é importante",
    mv_seo_why1_title: "Verificações de qualidade de masterização",
    mv_seo_why1_desc: "Certifique-se de que seus arquivos finais retenham a integridade. Quer saber <howto>como verificar a taxa de bits real do MP3 online</howto>? Verifique as taxas reais e os formatos de amostra para evitar redução silenciosa.",
    mv_seo_why2_title: "Conformidade de podcasts e streaming",
    mv_seo_why2_desc: "O Spotify e a Apple exigem padrões estritos de codificação. Valide os modos de canal estéreo, inspecione os carimbos de data/hora e certifique-se de que as tags estejam embutidas antes da publicação.",
    mv_seo_why3_title: "Análise Forense e Integridade de Arquivo",
    mv_seo_why3_desc: "Descubra traços de origem sem comprometer a privacidade do arquivo. Atue como um <free>verificador gratuito de integridade e checksum</free> para auditar cabeçalhos de stream e validar hashes.",
    mv_seo_h2_adv: "A vantagem da inspeção",
    mv_seo_adv_th1: "Capacidade de Recurso",
    mv_seo_adv_th2: "Leitores básicos online",
    mv_seo_adv_th3: "Nosso Inspetor Profundo",
    mv_seo_adv_r1c1: "ID3 Padrão (Título, Artista)",
    mv_seo_adv_r2c1: "Privacidade e Segurança de Dados",
    mv_seo_adv_r2c2: "Requer upload de servidor",
    mv_seo_adv_r2c3: "Execução 100% Local do Lado do Cliente",
    mv_seo_adv_r3c1: "Checksums de Hash (MD5/SHA)",
    mv_seo_adv_r3c2: "Ausente",
    mv_seo_adv_r4c1: "Taxa de Bits Real e Formatos",
    mv_seo_adv_r4c2: "Frequentemente estimativas",
    mv_seo_adv_r4c3: "Dados Exatos de Sonda do Decodificador",
    mv_seo_adv_r5c1: "Disposições de Stream e Flags",
    mv_seo_adv_r5c2: "Ausente",
    mv_seo_adv_r5c3: "Acessibilidade Completa e Flags de Codec",
    mv_seo_adv_r6c1: "Timestamps de Codec Avançados (PTS)",
    mv_seo_adv_r6c2: "Ausente",
    mv_seo_h2_faq: "Perguntas Frequentes",
    mv_seo_faq1_q: "Meus arquivos de áudio não lançados estão seguros?",
    mv_seo_faq1_a: "Absolutamente. Esta ferramenta utiliza APIs do navegador e WebAssembly para analisar binários de arquivo diretamente na memória do seu dispositivo. <no>Nenhum arquivo de áudio é enviado para nenhum servidor.</no> Você pode até se desconectar da internet após o carregamento da página.",
    mv_seo_faq2_q: "Qual é a diferença entre as tags ID3 e as propriedades do stream?",
    mv_seo_faq2_a: "<id3>Tags ID3</id3> são metadados editáveis anexados ao arquivo. <stream>Propriedades do stream</stream> são as instruções matemáticas brutas e ineditáveis que informam ao hardware como decodificar. Nossa ferramenta expõe ambos para <inspect>inspecionar perfeitamente as tags e formato de amostra</inspect>.",
    mv_seo_faq3_q: "Como o teste profundo de codec funciona localmente sem a instalação de software?",
    mv_seo_faq3_a: "Historicamente exigia ferramentas de linha de comando como o FFprobe. Como uma completa <online>ferramenta FFprobe online</online>, aproveitamos <wasm>WebAssembly</wasm> e mecanismos JavaScript de alto desempenho para executar a lógica de análise binária diretamente no navegador.",
    mv_seo_faq4_q: "Posso detectar áudio de alta resolução falso ou com upsampling?",
    mv_seo_faq4_a: "Sim. Ao comparar a taxa de bits ID3 declarada com a <true>Taxa de bits real</true> e o <sample>Formato de amostra</sample> extraídos do stream, os profissionais podem identificar discrepâncias em arquivos artificialmente inflados."
  }
};

locales.forEach(loc => {
  const file = path.join('messages', `${loc}.json`);
  let content = JSON.parse(fs.readFileSync(file, 'utf8'));
  Object.assign(content, translations[loc]);
  fs.writeFileSync(file, JSON.stringify(content, null, 2));
});

console.log("SEO Translations injected.");
