const fs = require('fs');
const path = require('path');

const translations = {
  ja: {
    'Drag and drop your M4A files or iPhone Voice Memos directly onto the converter stage. Because there is <strong>zero upload required</strong>, our web app instantly reads the local file buffer using the HTML5 File API. It immediately parses the file headers, identifies the AAC or ALAC codec, and prepares the binary stream for processing without waiting for a server connection.': 'M4AファイルやiPhoneのボイスメモを直接コンバーターにドラッグ＆ドロップしてください。<strong>アップロードは一切不要</strong>なため、当社のウェブアプリはHTML5 File APIを使用してローカルのファイルバッファを瞬時に読み込みます。サーバー接続を待つことなく、すぐにファイルヘッダーを解析し、AACまたはALACコーデックを特定して、バイナリストリームの処理準備を整えます。',
    'Client-Side Encoding': 'クライアントサイド・エンコーディング',
    'This is where the magic happens. Our embedded <strong>LAME v3.1 encoder</strong>, compiled to WebAssembly, springs into action. Using your device&apos;s own CPU and RAM, it perfectly transcodes the audio bit-by-bit from M4A into a universally compatible MP3 format. Advanced dithering algorithms ensure that harmonic distortion is minimized and the original dynamic range is preserved.': 'ここで魔法が起こります。WebAssemblyにコンパイルされた当社の組み込み<strong>LAME v3.1エンコーダ</strong>が作動します。お使いのデバイスのCPUとRAMを使用して、M4Aから普遍的に互換性のあるMP3フォーマットへ、音声をビット単位で完璧にトランスコードします。高度なディザリングアルゴリズムにより、高調波歪みが最小限に抑えられ、元のダイナミックレンジが維持されます。',
    'Secure Download': '安全なダウンロード',
    'Once the CPU finishes the transcoding cycle, the new MP3 file is generated directly in your browser&apos;s local memory. A secure Blob URL is created, triggering an immediate download to your local hard drive or smartphone storage. Fast, incredibly efficient, and mathematically impossible for us to access your data.': 'CPUがトランスコードサイクルを完了すると、ブラウザのローカルメモリに直接新しいMP3ファイルが生成されます。安全なBlob URLが作成され、ローカルハードドライブやスマートフォンのストレージへの即時ダウンロードがトリガーされます。高速で驚くほど効率的であり、当社があなたのデータにアクセスすることは数学的に不可能です。',
    '<strong>Absolutely not.</strong> Our application strictly adheres to a zero-upload architecture. All audio processing, decoding, and MP3 encoding happens locally inside your web browser using WebAssembly. Your files never touch our servers, meaning we never see, store, or transmit your private audio. It is mathematically impossible for us to access your data.': '<strong>絶対にありません。</strong> 当社のアプリケーションはゼロ・アップロード・アーキテクチャを厳格に遵守しています。音声処理、デコード、MP3エンコードはすべて、WebAssemblyを使用してウェブブラウザ内でローカルに行われます。ファイルが当社のサーバーに触れることは決してないため、お客様のプライベートな音声を見たり、保存したり、送信したりすることは決してありません。当社がデータにアクセスすることは数学的に不可能です。',
    '<strong>M4A</strong> is an audio container primarily used by Apple. It generally uses the Advanced Audio Coding (AAC) codec, which offers excellent sound quality at lower bitrates. However, it often fails to play on non-Apple devices. <strong>MP3</strong> is the undisputed universal standard for digital audio. Converting your M4A to MP3 ensures flawless playback on older car stereos, smart TVs, Windows PCs, Android devices, and legacy hardware.': '<strong>M4A</strong>は主にAppleが使用しているオーディオコンテナです。一般的にAdvanced Audio Coding (AAC) コーデックを使用し、低いビットレートでも優れた音質を提供します。しかし、Apple以外のデバイスでは再生できないことがよくあります。<strong>MP3</strong>はデジタルオーディオの揺るぎない世界標準です。M4AをMP3に変換することで、古いカーステレオ、スマートテレビ、Windows PC、Androidデバイス、レガシーハードウェアでの完璧な再生が保証されます。'
  },
  es: {
    'Drag and drop your M4A files or iPhone Voice Memos directly onto the converter stage. Because there is <strong>zero upload required</strong>, our web app instantly reads the local file buffer using the HTML5 File API. It immediately parses the file headers, identifies the AAC or ALAC codec, and prepares the binary stream for processing without waiting for a server connection.': 'Arrastra y suelta tus archivos M4A o notas de voz del iPhone directamente en el convertidor. Como <strong>no se requiere ninguna subida</strong>, nuestra aplicación web lee instantáneamente el archivo local utilizando la API de Archivos HTML5. Analiza de inmediato los encabezados del archivo, identifica el códec AAC o ALAC y prepara el flujo binario para su procesamiento sin esperar una conexión al servidor.',
    'Client-Side Encoding': 'Codificación del lado del cliente',
    'This is where the magic happens. Our embedded <strong>LAME v3.1 encoder</strong>, compiled to WebAssembly, springs into action. Using your device&apos;s own CPU and RAM, it perfectly transcodes the audio bit-by-bit from M4A into a universally compatible MP3 format. Advanced dithering algorithms ensure that harmonic distortion is minimized and the original dynamic range is preserved.': 'Aquí es donde ocurre la magia. Nuestro <strong>codificador LAME v3.1</strong> integrado, compilado en WebAssembly, entra en acción. Utilizando la CPU y RAM de tu propio dispositivo, transcodifica perfectamente el audio bit a bit de M4A a un formato MP3 universalmente compatible. Los algoritmos avanzados aseguran que la distorsión armónica se minimice y se preserve el rango dinámico original.',
    'Secure Download': 'Descarga Segura',
    'Once the CPU finishes the transcoding cycle, the new MP3 file is generated directly in your browser&apos;s local memory. A secure Blob URL is created, triggering an immediate download to your local hard drive or smartphone storage. Fast, incredibly efficient, and mathematically impossible for us to access your data.': 'Una vez que la CPU finaliza el ciclo de transcodificación, el nuevo archivo MP3 se genera directamente en la memoria local de tu navegador. Se crea una URL de tipo Blob segura, activando una descarga inmediata a tu disco duro local o almacenamiento del teléfono. Rápido, increíblemente eficiente y es matemáticamente imposible que nosotros accedamos a tus datos.',
    '<strong>Absolutely not.</strong> Our application strictly adheres to a zero-upload architecture. All audio processing, decoding, and MP3 encoding happens locally inside your web browser using WebAssembly. Your files never touch our servers, meaning we never see, store, or transmit your private audio. It is mathematically impossible for us to access your data.': '<strong>Absolutamente no.</strong> Nuestra aplicación se adhiere estrictamente a una arquitectura de cero subidas. Todo el procesamiento de audio, decodificación y codificación MP3 ocurre localmente dentro de tu navegador web usando WebAssembly. Tus archivos nunca tocan nuestros servidores, lo que significa que nunca vemos, almacenamos o transmitimos tu audio privado. Es matemáticamente imposible para nosotros acceder a tus datos.',
    '<strong>M4A</strong> is an audio container primarily used by Apple. It generally uses the Advanced Audio Coding (AAC) codec, which offers excellent sound quality at lower bitrates. However, it often fails to play on non-Apple devices. <strong>MP3</strong> is the undisputed universal standard for digital audio. Converting your M4A to MP3 ensures flawless playback on older car stereos, smart TVs, Windows PCs, Android devices, and legacy hardware.': '<strong>M4A</strong> es un contenedor de audio utilizado principalmente por Apple. Generalmente usa el códec Advanced Audio Coding (AAC), que ofrece una excelente calidad de sonido a bajas tasas de bits. Sin embargo, a menudo falla al reproducirse en dispositivos que no son de Apple. <strong>MP3</strong> es el estándar universal indiscutible para audio digital. Convertir tu M4A a MP3 asegura una reproducción impecable en radios de coches antiguos, televisores inteligentes, PCs con Windows, dispositivos Android y hardware heredado.'
  },
  de: {
    'Drag and drop your M4A files or iPhone Voice Memos directly onto the converter stage. Because there is <strong>zero upload required</strong>, our web app instantly reads the local file buffer using the HTML5 File API. It immediately parses the file headers, identifies the AAC or ALAC codec, and prepares the binary stream for processing without waiting for a server connection.': 'Ziehen Sie Ihre M4A-Dateien oder iPhone-Sprachmemos per Drag & Drop direkt auf den Konverter. Da <strong>kein Upload erforderlich</strong> ist, liest unsere Web-App den lokalen Dateipuffer mithilfe der HTML5-Datei-API sofort aus. Sie analysiert umgehend die Dateiheader, identifiziert den AAC- oder ALAC-Codec und bereitet den binären Stream für die Verarbeitung vor, ohne auf eine Serververbindung zu warten.',
    'Client-Side Encoding': 'Clientseitige Codierung',
    'This is where the magic happens. Our embedded <strong>LAME v3.1 encoder</strong>, compiled to WebAssembly, springs into action. Using your device&apos;s own CPU and RAM, it perfectly transcodes the audio bit-by-bit from M4A into a universally compatible MP3 format. Advanced dithering algorithms ensure that harmonic distortion is minimized and the original dynamic range is preserved.': 'Hier passiert die Magie. Unser eingebetteter <strong>LAME v3.1-Encoder</strong>, der in WebAssembly kompiliert wurde, tritt in Aktion. Er nutzt die CPU und den RAM Ihres eigenen Geräts, um das Audio Bit für Bit perfekt von M4A in ein universell kompatibles MP3-Format zu transcodieren. Fortschrittliche Dithering-Algorithmen stellen sicher, dass harmonische Verzerrungen minimiert werden und der ursprüngliche Dynamikumfang erhalten bleibt.',
    'Secure Download': 'Sicherer Download',
    'Once the CPU finishes the transcoding cycle, the new MP3 file is generated directly in your browser&apos;s local memory. A secure Blob URL is created, triggering an immediate download to your local hard drive or smartphone storage. Fast, incredibly efficient, and mathematically impossible for us to access your data.': 'Sobald die CPU den Transcodierungszyklus abgeschlossen hat, wird die neue MP3-Datei direkt im lokalen Speicher Ihres Browsers generiert. Es wird eine sichere Blob-URL erstellt, die einen sofortigen Download auf Ihre lokale Festplatte oder den Speicher Ihres Smartphones auslöst. Schnell, unglaublich effizient und es ist mathematisch unmöglich, dass wir auf Ihre Daten zugreifen.',
    '<strong>Absolutely not.</strong> Our application strictly adheres to a zero-upload architecture. All audio processing, decoding, and MP3 encoding happens locally inside your web browser using WebAssembly. Your files never touch our servers, meaning we never see, store, or transmit your private audio. It is mathematically impossible for us to access your data.': '<strong>Absolut nicht.</strong> Unsere Anwendung hält sich strikt an eine Zero-Upload-Architektur. Die gesamte Audioverarbeitung, Dekodierung und MP3-Codierung erfolgt lokal in Ihrem Webbrowser mithilfe von WebAssembly. Ihre Dateien berühren niemals unsere Server, was bedeutet, dass wir Ihr privates Audio niemals sehen, speichern oder übertragen. Es ist mathematisch unmöglich für uns, auf Ihre Daten zuzugreifen.',
    '<strong>M4A</strong> is an audio container primarily used by Apple. It generally uses the Advanced Audio Coding (AAC) codec, which offers excellent sound quality at lower bitrates. However, it often fails to play on non-Apple devices. <strong>MP3</strong> is the undisputed universal standard for digital audio. Converting your M4A to MP3 ensures flawless playback on older Autoradios, Smart-TVs, Windows-PCs, Android-Geräten und älterer Hardware.': '<strong>M4A</strong> ist ein Audio-Container, der hauptsächlich von Apple verwendet wird. Er verwendet im Allgemeinen den Advanced Audio Coding (AAC)-Codec, der bei niedrigeren Bitraten eine hervorragende Klangqualität bietet. Auf Nicht-Apple-Geräten schlägt die Wiedergabe jedoch häufig fehl. <strong>MP3</strong> ist der unbestrittene universelle Standard für digitales Audio. Die Konvertierung Ihres M4A in MP3 gewährleistet eine einwandfreie Wiedergabe auf älteren Autoradios, Smart-TVs, Windows-PCs, Android-Geräten und älterer Hardware.'
  },
  pt: {
    'Drag and drop your M4A files or iPhone Voice Memos directly onto the converter stage. Because there is <strong>zero upload required</strong>, our web app instantly reads the local file buffer using the HTML5 File API. It immediately parses the file headers, identifies the AAC or ALAC codec, and prepares the binary stream for processing without waiting for a server connection.': 'Arraste e solte seus arquivos M4A ou Memos de Voz do iPhone diretamente no conversor. Como <strong>não é necessário nenhum upload</strong>, nosso aplicativo web lê instantaneamente o buffer do arquivo local usando a API de Arquivo HTML5. Ele analisa imediatamente os cabeçalhos do arquivo, identifica o codec AAC ou ALAC e prepara o fluxo binário para processamento sem esperar por uma conexão com o servidor.',
    'Client-Side Encoding': 'Codificação no Cliente',
    'This is where the magic happens. Our embedded <strong>LAME v3.1 encoder</strong>, compiled to WebAssembly, springs into action. Using your device&apos;s own CPU and RAM, it perfectly transcodes the audio bit-by-bit from M4A into a universally compatible MP3 format. Advanced dithering algorithms ensure that harmonic distortion is minimized and the original dynamic range is preserved.': 'É aqui que a mágica acontece. Nosso <strong>codificador LAME v3.1</strong> integrado, compilado para WebAssembly, entra em ação. Usando a própria CPU e RAM do seu dispositivo, ele transcodifica perfeitamente o áudio bit a bit de M4A para um formato MP3 universalmente compatível. Algoritmos avançados garantem que a distorção harmônica seja minimizada e o alcance dinâmico original seja preservado.',
    'Secure Download': 'Download Seguro',
    'Once the CPU finishes the transcoding cycle, the new MP3 file is generated directly in your browser&apos;s local memory. A secure Blob URL is created, triggering an immediate download to your local hard drive or smartphone storage. Fast, incredibly efficient, and mathematically impossible for us to access your data.': 'Assim que a CPU termina o ciclo de transcodificação, o novo arquivo MP3 é gerado diretamente na memória local do seu navegador. Um URL Blob seguro é criado, acionando um download imediato para o disco rígido local ou armazenamento do smartphone. Rápido, incrivelmente eficiente e matematicamente impossível para nós acessarmos seus dados.',
    '<strong>Absolutely not.</strong> Our application strictly adheres to a zero-upload architecture. All audio processing, decoding, and MP3 encoding happens locally inside your web browser using WebAssembly. Your files never touch our servers, meaning we never see, store, or transmit your private audio. It is mathematically impossible for us to access your data.': '<strong>Absolutamente não.</strong> Nosso aplicativo adere estritamente a uma arquitetura de upload zero. Todo o processamento de áudio, decodificação e codificação MP3 acontece localmente dentro do seu navegador da web usando WebAssembly. Seus arquivos nunca tocam nossos servidores, o que significa que nunca vemos, armazenamos ou transmitimos seu áudio privado. É matematicamente impossível para nós acessarmos seus dados.',
    '<strong>M4A</strong> is an audio container primarily used by Apple. It generally uses the Advanced Audio Coding (AAC) codec, which offers excellent sound quality at lower bitrates. However, it often fails to play on non-Apple devices. <strong>MP3</strong> is the undisputed universal standard for digital audio. Converting your M4A to MP3 ensures flawless playback on older car stereos, smart TVs, Windows PCs, Android devices, and legacy hardware.': '<strong>M4A</strong> é um contêiner de áudio usado principalmente pela Apple. Geralmente usa o codec Advanced Audio Coding (AAC), que oferece excelente qualidade de som em taxas de bits mais baixas. No entanto, muitas vezes falha ao reproduzir em dispositivos não-Apple. O <strong>MP3</strong> é o padrão universal indiscutível para áudio digital. Converter seu M4A para MP3 garante uma reprodução impecável em aparelhos de som automotivos mais antigos, smart TVs, PCs com Windows, dispositivos Android e hardware legado.'
  },
  fr: {
    'Drag and drop your M4A files or iPhone Voice Memos directly onto the converter stage. Because there is <strong>zero upload required</strong>, our web app instantly reads the local file buffer using the HTML5 File API. It immediately parses the file headers, identifies the AAC or ALAC codec, and prepares the binary stream for processing without waiting for a server connection.': 'Glissez et déposez vos fichiers M4A ou mémos vocaux iPhone directement dans le convertisseur. Puisqu&apos;il n&apos;y a <strong>aucun téléchargement requis</strong>, notre application web lit instantanément le tampon de fichier local à l&apos;aide de l&apos;API de Fichier HTML5. Elle analyse immédiatement les en-têtes du fichier, identifie le codec AAC ou ALAC, et prépare le flux binaire pour le traitement sans attendre de connexion au serveur.',
    'Client-Side Encoding': 'Encodage Côté Client',
    'This is where the magic happens. Our embedded <strong>LAME v3.1 encoder</strong>, compiled to WebAssembly, springs into action. Using your device&apos;s own CPU and RAM, it perfectly transcodes the audio bit-by-bit from M4A into a universally compatible MP3 format. Advanced dithering algorithms ensure that harmonic distortion is minimized and the original dynamic range is preserved.': 'C&apos;est ici que la magie opère. Notre <strong>encodeur LAME v3.1</strong> intégré, compilé en WebAssembly, entre en action. En utilisant le CPU et la RAM de votre propre appareil, il transcode parfaitement l&apos;audio bit par bit de M4A vers un format MP3 universellement compatible. Des algorithmes avancés garantissent que la distorsion harmonique est minimisée et la plage dynamique originale préservée.',
    'Secure Download': 'Téléchargement Sécurisé',
    'Once the CPU finishes the transcoding cycle, the new MP3 file is generated directly in your browser&apos;s local memory. A secure Blob URL is created, triggering an immediate download to your local hard drive or smartphone storage. Fast, incredibly efficient, and mathematically impossible for us to access your data.': 'Une fois que le processeur a terminé le cycle de transcodage, le nouveau fichier MP3 est généré directement dans la mémoire locale de votre navigateur. Une URL Blob sécurisée est créée, déclenchant un téléchargement immédiat sur votre disque dur local ou le stockage de votre smartphone. Rapide, incroyablement efficace, et mathématiquement impossible pour nous d&apos;accéder à vos données.',
    '<strong>Absolutely not.</strong> Our application strictly adheres to a zero-upload architecture. All audio processing, decoding, and MP3 encoding happens locally inside your web browser using WebAssembly. Your files never touch our servers, meaning we never see, store, or transmit your private audio. It is mathematically impossible for us to access your data.': '<strong>Absolument pas.</strong> Notre application adhère strictement à une architecture zéro téléchargement. Tout le traitement audio, le décodage et l&apos;encodage MP3 se produisent localement dans votre navigateur web en utilisant WebAssembly. Vos fichiers ne touchent jamais nos serveurs, ce qui signifie que nous ne voyons, ne stockons, ni ne transmettons jamais votre audio privé. Il est mathématiquement impossible pour nous d&apos;accéder à vos données.',
    '<strong>M4A</strong> is an audio container primarily used by Apple. It generally uses the Advanced Audio Coding (AAC) codec, which offers excellent sound quality at lower bitrates. However, it often fails to play on non-Apple devices. <strong>MP3</strong> is the undisputed universal standard for digital audio. Converting your M4A to MP3 ensures flawless playback on older car stereos, smart TVs, Windows PCs, Android devices, and legacy hardware.': '<strong>M4A</strong> est un conteneur audio principalement utilisé par Apple. Il utilise généralement le codec Advanced Audio Coding (AAC), qui offre une excellente qualité sonore à des débits binaires inférieurs. Cependant, il échoue souvent à être lu sur des appareils non-Apple. Le <strong>MP3</strong> est la norme universelle incontestée pour l&apos;audio numérique. La conversion de votre M4A en MP3 garantit une lecture sans faille sur les anciens autoradios, les smart TVs, les PC Windows, les appareils Android et l&apos;ancien matériel.'
  }
};

for (const lang of Object.keys(translations)) {
  const filePath = path.join(__dirname, '../app', lang, 'page.tsx');
  if (!fs.existsSync(filePath)) continue;
  
  let content = fs.readFileSync(filePath, 'utf8');
  const dict = translations[lang];
  
  for (const [enText, translatedText] of Object.entries(dict)) {
    // Basic replacement. If there's slight formatting mismatch, we may need regex.
    // Try literal replace first
    if (content.includes(enText)) {
      content = content.replace(enText, translatedText);
    } else {
      console.log(`Warning: Could not find exact match for text in ${lang}: ${enText.substring(0, 30)}...`);
    }
  }
  
  // also fix one small bug in German translation (copy-pasted English instead of translated list of devices)
  content = content.replace(
      'Converting your M4A to MP3 ensures flawless playback on older car stereos, smart TVs, Windows PCs, Android devices, and legacy hardware.', 
      'Converting your M4A to MP3 ensures flawless playback on older Autoradios, Smart-TVs, Windows-PCs, Android-Geräten und älterer Hardware.'
  );

  fs.writeFileSync(filePath, content);
  console.log(`Injected hardcoded translations for ${lang}`);
}

